"use client";
import Link from"next/link";import{useCallback,useEffect,useState}from"react";import{Logo}from"@/components/ui";import{CerrarSesion}from"@/components/cerrar-sesion";import{QRAcceso}from"@/components/qr-acceso";
type Balance={available:number;pending:number;total:number;redeemed:number};type Tx={id:string;points:number;status:string;concept:string;created_at:string};type Reward={slug:string;name:string;description:string;points_required:number;stock:number;terms:string;venues?:{name?:string}|null};type Redemption={id:string;token:string;points:number;status:string;expires_at:string;loyalty_rewards?:{name?:string;venues?:{name?:string}|null}|null};type Mission={slug:string;name:string;description:string;reward_points:number;ends_at:string;requires_audit:boolean};type Execution={id:string;status:string;points_awarded?:number;review_notes?:string;loyalty_missions?:{slug?:string;name?:string}|null};type Payload={balance:Balance;transactions:Tx[];rewards:Reward[];redemptions:Redemption[];missions:Mission[];executions:Execution[]};
const LEVELS=[{name:"Bronce",min:0,next:500},{name:"Plata",min:500,next:1500},{name:"Oro",min:1500,next:3500},{name:"Black",min:3500,next:3500}];
export default function MiNocta(){const[data,setData]=useState<Payload>();const[error,setError]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const load=useCallback(async()=>{const r=await fetch("/api/loyalty",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error??"No fue posible cargar Mi NOCTA");setData(d)},[]);useEffect(()=>{let active=true;void fetch("/api/loyalty",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error??"No fue posible cargar Mi NOCTA");if(active)setData(d)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Error")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
async function act(body:Record<string,unknown>,key:string){setBusy(key);setError("");const idempotencyKey=crypto.randomUUID();const r=await fetch("/api/loyalty",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify({...body,idempotencyKey})});const d=await r.json();if(!r.ok)setError(d.error??"No fue posible completar la operación");else await load();setBusy("")}
if(loading)return<main className="p-8 text-muted">Cargando Mi NOCTA…</main>;if(!data)return<main className="p-8"><p className="text-danger">{error}</p><Link href="/">← Volver</Link></main>;const level=[...LEVELS].reverse().find(x=>data.balance.total>=x.min)??LEVELS[0];const progress=level.name==="Black"?100:Math.min(100,data.balance.total/level.next*100);const executionBySlug=new Map(data.executions.map(e=>[e.loyalty_missions?.slug,e]));
return<main className="flex-1 px-5 py-8 max-w-5xl mx-auto w-full space-y-7"><header className="flex justify-between gap-3"><div><Logo size="text-3xl"/><p className="text-xs uppercase tracking-[.2em] text-neon3 mt-2">Comunidad y beneficios</p></div><div className="flex gap-3 items-center"><Link href="/" className="text-sm text-muted">← Explorar</Link><CerrarSesion/></div></header>
<section className="card p-6"><p className="text-xs uppercase tracking-[.2em] text-neon2">Nivel {level.name}</p><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4"><Kpi t="Disponibles" v={data.balance.available}/><Kpi t="Pendientes" v={data.balance.pending}/><Kpi t="Ganados" v={data.balance.total}/><Kpi t="Redimidos" v={data.balance.redeemed}/></div><div className="h-2 bg-surface2 rounded-full mt-5"><div className="h-full bg-gradient-to-r from-neon1 to-neon2 rounded-full" style={{width:`${progress}%`}}/></div></section>{error&&<p role="alert" className="rounded-xl border border-danger/40 bg-danger/10 p-3 text-danger">{error}</p>}
<section><h1 className="text-2xl font-bold">Misiones</h1><p className="text-sm text-muted">Completa actividades y recibe puntos cuando sean aprobadas.</p><div className="grid md:grid-cols-2 gap-3 mt-4">{data.missions.map(m=>{const execution=executionBySlug.get(m.slug);return<article key={m.slug} className="card p-5"><div className="flex justify-between gap-3"><div><h2 className="font-bold text-lg">{m.name}</h2><p className="text-sm text-muted">{m.description}</p></div><b className="text-lime">+{m.reward_points}</b></div><p className="text-xs text-muted mt-3">{m.requires_audit?"Requiere revisión":"Aprobación automática"} · hasta {new Date(m.ends_at).toLocaleDateString("es-CO")}</p>{execution?<p className="rounded-xl bg-surface2 p-3 mt-4 text-sm">Estado: <b>{execution.status}</b>{execution.review_notes&&` · ${execution.review_notes}`}</p>:<button onClick={()=>act({action:"execute",missionSlug:m.slug,evidence:{}},m.slug)} disabled={Boolean(busy)} className="btn-neon rounded-xl p-3 mt-4 w-full disabled:opacity-40">{busy===m.slug?"Enviando…":"Completar misión"}</button>}</article>})}{!data.missions.length&&<p className="card p-8 text-muted">No hay misiones activas.</p>}</div></section>
<section><h2 className="text-2xl font-bold">Beneficios</h2><div className="grid md:grid-cols-3 gap-3 mt-4">{data.rewards.map(r=><article key={r.slug} className="card p-5 flex flex-col"><p className="text-xs text-neon3">{r.venues?.name} · stock {r.stock}</p><h3 className="text-xl font-bold mt-2">{r.name}</h3><p className="text-sm text-muted mt-2 flex-1">{r.description}</p><p className="font-bold mt-4">{r.points_required} puntos</p><button onClick={()=>act({action:"redeem",rewardSlug:r.slug},r.slug)} disabled={r.stock<1||data.balance.available<r.points_required||Boolean(busy)} className="btn-neon rounded-xl p-3 mt-3 disabled:opacity-40">{busy===r.slug?"Reservando…":r.stock<1?"Agotado":data.balance.available<r.points_required?"Puntos insuficientes":"Reservar por 24 horas"}</button></article>)}</div></section>
{data.redemptions.length>0&&<section><h2 className="text-2xl font-bold">Mis redenciones</h2><div className="grid md:grid-cols-2 gap-3 mt-4">{data.redemptions.map(r=><article key={r.id} className="card p-5 text-center">{r.status==="requested"&&<QRAcceso contenido={r.token} alt="Token de redención"/>}<b className="block mt-3">{r.loyalty_rewards?.name}</b><p className="text-xs text-muted">{r.loyalty_rewards?.venues?.name}</p><p className="font-mono text-neon3 mt-2">{r.token}</p><p className="text-xs mt-2">{r.status} · vence {new Date(r.expires_at).toLocaleString("es-CO")}</p></article>)}</div></section>}
<section><h2 className="text-2xl font-bold">Libro de movimientos</h2><div className="card mt-4 overflow-hidden">{data.transactions.map(tx=><div key={tx.id} className="p-4 border-b border-line flex justify-between"><div><b>{tx.concept}</b><p className="text-xs text-muted">{tx.status} · {new Date(tx.created_at).toLocaleString("es-CO")}</p></div><b className={tx.points>0?"text-lime":"text-amber"}>{tx.points>0?"+":""}{tx.points}</b></div>)}{!data.transactions.length&&<p className="p-8 text-center text-muted">Aún no tienes movimientos.</p>}</div></section></main>}
function Kpi({t,v}:{t:string;v:number}){return<div><p className="text-xs text-muted">{t}</p><p className="text-2xl font-bold">{v.toLocaleString("es-CO")}</p></div>}
