"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Campaign = { id: string; name: string; budget_points: number; status: string; starts_at?: string; ends_at?: string };
type Data = { campaigns: Campaign[]; missions: Array<{ id: string; name: string; reward_points: number; status: string }>; rewards: Array<{ id: string; name: string; points_required: number; stock: number; venues?: { name?: string } | null }>; executions: Array<{ id: string; evidence: Record<string, unknown>; profiles?: { full_name?: string } | null; loyalty_missions?: { name?: string; reward_points?: number } | null }>; venues: Array<{ id: string; name: string }> };
type FormKind = "campaign" | "mission" | "reward";

export default function FidelidadAdmin() {
  const [data, setData] = useState<Data>();
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState("");
  const [form, setForm] = useState<FormKind>("campaign");

  const load = useCallback(async () => { const response = await fetch("/api/admin/loyalty", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "No fue posible cargar fidelización"); setData(body); }, []);
  useEffect(() => {
    let active = true;
    void fetch("/api/admin/loyalty", { cache: "no-store" }).then(async (response) => {
      const body = await response.json();
      if (!response.ok) throw new Error(body.error ?? "No fue posible cargar fidelización");
      if (active) setData(body);
    }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Error"); });
    return () => { active = false; };
  }, []);

  async function send(body: Record<string, unknown>, success: string) {
    setBusy(String(body.action)); setError(""); setNotice("");
    const requestKey = crypto.randomUUID();
    try { const response = await fetch("/api/admin/loyalty", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": requestKey }, body: JSON.stringify({ ...body, idempotencyKey: requestKey }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "No fue posible guardar"); setNotice(success); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Error"); }
    finally { setBusy(""); }
  }

  async function review(id: string, decision: string, notes = "") { await send({ action: "review", executionId: id, decision, notes }, "La revisión quedó registrada."); }
  if (!data) return <main className="p-8 text-muted">Preparando el centro de fidelización…</main>;

  return <main className="flex-1 px-5 py-8 max-w-7xl mx-auto space-y-7">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-neon3">Centro operativo</p><h1 className="text-3xl font-bold mt-1">Fidelización</h1><p className="text-muted">Diseña campañas, activa misiones, publica beneficios y aprueba evidencias.</p></div><button onClick={() => void load()} className="rounded-xl border border-line px-4 py-3">Actualizar datos</button></header>
    {error && <p role="alert" className="rounded-xl border border-danger/40 bg-danger/10 p-3 text-danger">{error}</p>}{notice && <p role="status" className="rounded-xl border border-lime/40 bg-lime/10 p-3 text-lime">{notice}</p>}
    <section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Box t="Campañas" v={data.campaigns.length}/><Box t="Misiones" v={data.missions.length}/><Box t="Beneficios" v={data.rewards.length}/><Box t="Por revisar" v={data.executions.length} attention={data.executions.length > 0}/></section>

    <section className="grid lg:grid-cols-[1.05fr_.95fr] gap-5">
      <div className="card p-5"><div className="flex flex-wrap gap-2 mb-5"><Tab active={form === "campaign"} onClick={() => setForm("campaign")}>Nueva campaña</Tab><Tab active={form === "mission"} onClick={() => setForm("mission")}>Nueva misión</Tab><Tab active={form === "reward"} onClick={() => setForm("reward")}>Nuevo beneficio</Tab></div>{form === "campaign" ? <CampaignForm busy={busy} submit={send}/> : form === "mission" ? <MissionForm campaigns={data.campaigns} busy={busy} submit={send}/> : <RewardForm venues={data.venues} busy={busy} submit={send}/>}</div>
      <section className="card p-5"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">Evidencias por revisar</h2><p className="text-sm text-muted">Cada decisión queda registrada en auditoría.</p></div>{data.executions.length > 0 && <span className="rounded-full bg-amber/15 text-amber px-3 py-1 h-fit text-sm">{data.executions.length}</span>}</div>{data.executions.map((execution) => <article key={execution.id} className="border-t border-line py-4 mt-4"><b>{execution.loyalty_missions?.name}</b><p className="text-sm text-muted">{execution.profiles?.full_name || "Participante"} · +{execution.loyalty_missions?.reward_points} puntos</p><dl className="bg-surface2 p-3 rounded-xl mt-3 text-sm space-y-2">{Object.entries(execution.evidence).map(([key, value]) => <div key={key}><dt className="text-xs text-muted">{key.replaceAll("_", " ")}</dt><dd className="break-words">{String(value)}</dd></div>)}</dl><div className="grid grid-cols-3 gap-2 mt-3"><button disabled={Boolean(busy)} onClick={() => { const notes = window.prompt("¿Qué debe corregir el participante?"); if (notes) void review(execution.id, "needs_fix", notes); }} className="border border-amber/40 rounded-xl p-3 text-sm">Corregir</button><button disabled={Boolean(busy)} onClick={() => void review(execution.id, "rejected", "Evidencia rechazada")} className="border border-danger/40 text-danger rounded-xl p-3 text-sm">Rechazar</button><button disabled={Boolean(busy)} onClick={() => void review(execution.id, "approved")} className="btn-neon rounded-xl p-3 text-sm">Aprobar</button></div></article>)}{!data.executions.length && <div className="py-12 text-center"><p className="text-3xl">✓</p><p className="font-semibold mt-2">Todo al día</p><p className="text-sm text-muted">No hay evidencias pendientes.</p></div>}</section>
    </section>

    <section className="grid lg:grid-cols-3 gap-4"><List title="Campañas">{data.campaigns.map((item) => <Row key={item.id} title={item.name} detail={`${item.status} · ${item.budget_points.toLocaleString("es-CO")} puntos`}/>)}</List><List title="Misiones">{data.missions.map((item) => <Row key={item.id} title={item.name} detail={`${item.status} · +${item.reward_points} puntos`}/>)}</List><List title="Beneficios">{data.rewards.map((item) => <Row key={item.id} title={item.name} detail={`${item.venues?.name ?? "Sin establecimiento"} · ${item.points_required} pts · stock ${item.stock}`}/>)}</List></section>
  </main>;
}

function CampaignForm({ busy, submit }: { busy: string; submit: (body: Record<string, unknown>, success: string) => Promise<void> }) { return <Form title="Crear campaña" description="Define el presupuesto total y la ventana operativa." busy={busy === "campaign"} onSubmit={(form) => submit({ action: "campaign", name: form.get("name"), budgetPoints: Number(form.get("budget")), status: form.get("status"), startsAt: iso(form.get("starts")), endsAt: iso(form.get("ends")) }, "Campaña creada.")}><Field name="name" label="Nombre" required/><div className="grid grid-cols-2 gap-3"><Field name="budget" label="Presupuesto en puntos" type="number" min="1" required/><Select name="status" label="Estado" options={["draft", "scheduled", "published"]}/></div><div className="grid grid-cols-2 gap-3"><Field name="starts" label="Inicio" type="datetime-local" required/><Field name="ends" label="Fin" type="datetime-local" required/></div></Form>; }
function MissionForm({ campaigns, busy, submit }: { campaigns: Campaign[]; busy: string; submit: (body: Record<string, unknown>, success: string) => Promise<void> }) { return <Form title="Crear misión" description="La evidencia solicitada aparecerá como formulario para el participante." busy={busy === "mission"} onSubmit={(form) => { const required = String(form.get("evidence") ?? "").split(",").map((item) => item.trim().toLowerCase().replaceAll(" ", "_")).filter(Boolean); return submit({ action: "mission", campaignId: form.get("campaign"), slug: slug(String(form.get("name"))), name: form.get("name"), description: form.get("description"), rewardPoints: Number(form.get("points")), startsAt: iso(form.get("starts")), endsAt: iso(form.get("ends")), totalQuota: Number(form.get("totalQuota")), perUserQuota: Number(form.get("userQuota")), frequency: form.get("frequency"), requiresAudit: form.get("audit") === "on", evidenceSchema: { required } }, "Misión creada."); }}><Select name="campaign" label="Campaña" options={campaigns.map((item) => ({ value: item.id, label: item.name }))}/><Field name="name" label="Nombre" required/><Field name="description" label="Descripción" required/><div className="grid grid-cols-3 gap-3"><Field name="points" label="Puntos" type="number" min="1" required/><Field name="totalQuota" label="Cupo total" type="number" min="1" defaultValue="100" required/><Field name="userQuota" label="Por usuario" type="number" min="1" defaultValue="1" required/></div><div className="grid grid-cols-2 gap-3"><Field name="starts" label="Inicio" type="datetime-local" required/><Field name="ends" label="Fin" type="datetime-local" required/></div><Select name="frequency" label="Frecuencia" options={["once", "daily", "weekly", "monthly", "campaign"]}/><Field name="evidence" label="Campos de evidencia (separados por coma)" placeholder="enlace, comentario"/><label className="flex gap-2 text-sm"><input type="checkbox" name="audit" defaultChecked/> Requiere revisión humana</label></Form>; }
function RewardForm({ venues, busy, submit }: { venues: Data["venues"]; busy: string; submit: (body: Record<string, unknown>, success: string) => Promise<void> }) { return <Form title="Publicar beneficio" description="El inventario queda reservado de forma atómica al hacer un canje." busy={busy === "reward"} onSubmit={(form) => submit({ action: "reward", slug: slug(String(form.get("name"))), name: form.get("name"), description: form.get("description"), pointsRequired: Number(form.get("points")), stock: Number(form.get("stock")), venueId: form.get("venue"), city: form.get("city"), category: form.get("category"), terms: form.get("terms") }, "Beneficio publicado.")}><Select name="venue" label="Establecimiento autorizado" options={venues.map((item) => ({ value: item.id, label: item.name }))}/><Field name="name" label="Nombre" required/><Field name="description" label="Descripción" required/><div className="grid grid-cols-2 gap-3"><Field name="points" label="Costo en puntos" type="number" min="1" required/><Field name="stock" label="Inventario" type="number" min="0" required/></div><div className="grid grid-cols-2 gap-3"><Field name="city" label="Ciudad"/><Field name="category" label="Categoría"/></div><Field name="terms" label="Condiciones de uso" required/></Form>; }

function Form({ title, description, busy, onSubmit, children }: { title: string; description: string; busy: boolean; onSubmit: (form: FormData) => Promise<void>; children: React.ReactNode }) { return <form className="space-y-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void onSubmit(new FormData(event.currentTarget)).then(() => event.currentTarget.reset()); }}><div><h2 className="text-xl font-bold">{title}</h2><p className="text-sm text-muted">{description}</p></div>{children}<button disabled={busy} className="btn-neon rounded-xl p-3 w-full disabled:opacity-50">{busy ? "Guardando…" : "Guardar y continuar"}</button></form>; }
function Field(props: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { const { label, ...input } = props; return <label className="block text-sm"><span className="text-muted">{label}</span><input {...input} className="entrada mt-1"/></label>; }
function Select({ name, label, options }: { name: string; label: string; options: Array<string | { value: string; label: string }> }) { return <label className="block text-sm"><span className="text-muted">{label}</span><select name={name} required className="entrada mt-1 bg-background">{options.map((item) => typeof item === "string" ? <option key={item} value={item}>{item}</option> : <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>; }
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`rounded-full px-4 py-2 text-sm ${active ? "bg-neon3 text-black font-bold" : "bg-surface2 text-muted"}`}>{children}</button>; }
function Box({ t, v, attention }: { t: string; v: number; attention?: boolean }) { return <div className={`card p-5 ${attention ? "border-amber/50" : ""}`}><p className="text-xs text-muted">{t}</p><p className="text-3xl font-bold">{v}</p></div>; }
function List({ title, children }: { title: string; children: React.ReactNode }) { return <div className="card p-5"><h2 className="font-bold">{title}</h2><div className="mt-2">{children}</div></div>; }
function Row({ title, detail }: { title: string; detail: string }) { return <div className="border-t border-line py-3"><b className="text-sm">{title}</b><p className="text-xs text-muted">{detail}</p></div>; }
function iso(value: FormDataEntryValue | null) { return value ? new Date(String(value)).toISOString() : null; }
function slug(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
