"use client";

import Link from "next/link";
import { Logo } from "@/components/ui";
import { eventoPorId, lugarPorId } from "@/lib/discovery";
import { actualizarEstadoReserva, useReservas } from "@/lib/reservations";

export default function GestionReservas(){const reservas=useReservas();const pendientes=reservas.filter(r=>r.estado==="pendiente").length;const confirmadas=reservas.filter(r=>r.estado==="confirmada").length;const anticipos=reservas.filter(r=>["confirmada","usada"].includes(r.estado)).reduce((s,r)=>s+r.anticipo,0);return <main className="flex-1 px-5 py-8 max-w-5xl mx-auto w-full space-y-6"><header className="flex justify-between gap-4"><div><Logo size="text-3xl"/><h1 className="text-2xl font-bold mt-2">Gestión de reservas</h1></div><Link href="/accesos" className="text-sm text-muted">← Roles</Link></header><section className="grid grid-cols-3 gap-3"><Kpi t="Pendientes" v={pendientes}/><Kpi t="Confirmadas" v={confirmadas}/><Kpi t="Anticipos" v={`$${anticipos.toLocaleString("es-CO")}`}/></section><section className="space-y-3">{reservas.slice().reverse().map(r=>{const e=eventoPorId(r.eventoId);const l=e?lugarPorId(e.lugarId):undefined;return <article key={r.id} className="card p-5"><div className="flex justify-between gap-4"><div><p className="text-xs text-neon3">{l?.nombre} · {r.codigo}</p><h2 className="text-xl font-bold mt-1">{r.titular}</h2><p className="text-sm text-muted">{e?.nombre} · {r.tipoNombre} · {r.personas} personas</p><p className="text-xs text-muted mt-2">{r.telefono} · {r.email}{r.ocasion?` · ${r.ocasion}`:""}</p>{r.notas&&<p className="text-sm mt-2">“{r.notas}”</p>}</div><span className="uppercase text-xs font-bold">{r.estado}</span></div>{r.estado==="pendiente"&&<div className="flex gap-2 mt-4"><button onClick={()=>actualizarEstadoReserva(r.id,"rechazada")} className="flex-1 rounded-xl border border-danger/40 text-danger p-3">Rechazar</button><button onClick={()=>actualizarEstadoReserva(r.id,"confirmada")} className="btn-neon flex-1 rounded-xl p-3 font-bold">Confirmar</button></div>}{r.estado==="confirmada"&&<button onClick={()=>actualizarEstadoReserva(r.id,"usada")} className="mt-4 w-full rounded-xl border border-lime/40 text-lime p-3">Marcar llegada y completar</button>}</article>})}{!reservas.length&&<div className="card p-10 text-center text-muted">No hay solicitudes de reserva.</div>}</section></main>}
function Kpi({t,v}:{t:string;v:string|number}){return <div className="card p-4"><p className="text-xs text-muted">{t}</p><p className="text-xl font-bold mt-1">{v}</p></div>}
