"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { EVENTOS, LUGARES, lugarPorId } from "@/lib/discovery";

type Favorite = { entity_type: string; entity_key: string };
type Promotion = { id: string; title: string; description: string; terms: string; ends_at: string; venues?: { external_key?: string; name?: string; city?: string } | null; events?: { external_key?: string; name?: string } | null };
type Tab = "todo" | "eventos" | "lugares" | "promociones" | "favoritos";

export default function Explorar() {
  const [search, setSearch] = useState(""); const [tab, setTab] = useState<Tab>("todo"); const [category, setCategory] = useState("Todas");
  const [location, setLocation] = useState("Cartagena"); const [locating, setLocating] = useState(false); const [favorites, setFavorites] = useState<Favorite[]>([]); const [promotions, setPromotions] = useState<Promotion[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { let active = true; void fetch("/api/discovery", { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (active) { setPromotions(data.promotions ?? []); setFavorites(data.favorites ?? []); } }); return () => { active = false; }; }, []);
  const favorite = useCallback((type: string, key: string) => favorites.some((item) => item.entity_type === type && item.entity_key === key), [favorites]);
  async function toggle(type: string, key: string) { const next = !favorite(type, key); const response = await fetch("/api/discovery", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entityType: type, entityKey: key, favorite: next }) }); if (response.status === 401) { setMessage("Inicia sesión para guardar tus favoritos."); return; } if (response.ok) setFavorites((current) => next ? [...current, { entity_type: type, entity_key: key }] : current.filter((item) => item.entity_type !== type || item.entity_key !== key)); }
  function locate() { if (!navigator.geolocation) return setMessage("La ubicación no está disponible en este dispositivo."); setLocating(true); navigator.geolocation.getCurrentPosition(({ coords }) => { const cartagena = Math.abs(coords.latitude - 10.4) < 2 && Math.abs(coords.longitude + 75.5) < 2; setLocation(cartagena ? "Cartagena" : "Cerca de ti"); setLocating(false); }, () => { setMessage("No pudimos acceder a tu ubicación. Puedes seguir explorando Cartagena."); setLocating(false); }, { enableHighAccuracy: false, timeout: 8000 }); }
  const text = search.trim().toLowerCase();
  const venues = useMemo(() => LUGARES.filter((item) => (!text || [item.nombre, item.zona, item.categoria, ...item.estilos].some((value) => value.toLowerCase().includes(text))) && (category === "Todas" || item.categoria === category) && (tab !== "favoritos" || favorite("venue", item.id))), [text, category, tab, favorite]);
  const events = useMemo(() => EVENTOS.filter((item) => { const venue = lugarPorId(item.lugarId); return (!text || [item.nombre, item.resumen, venue?.nombre, ...item.generos].some((value) => value?.toLowerCase().includes(text))) && (tab !== "favoritos" || favorite("event", item.id)); }), [text, tab, favorite]);
  const visiblePromotions = promotions.filter((item) => (!text || [item.title, item.description, item.venues?.name].some((value) => value?.toLowerCase().includes(text))) && (tab !== "favoritos" || favorite("promotion", item.id)));
  const showEvents = tab === "todo" || tab === "eventos" || tab === "favoritos"; const showVenues = tab === "todo" || tab === "lugares" || tab === "favoritos"; const showPromotions = tab === "todo" || tab === "promociones" || tab === "favoritos";
  return <main className="flex-1 px-5 py-8 max-w-6xl mx-auto w-full space-y-8"><header><div className="flex items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-neon2">Explorar</p><h1 className="text-3xl md:text-5xl font-bold mt-2">¿Qué hacemos hoy?</h1></div><button onClick={locate} disabled={locating} className="rounded-full border border-line px-4 py-2 text-sm text-neon3">⌖ {locating ? "Ubicando…" : location}</button></div><div className="card p-2 flex items-center mt-6 max-w-3xl"><span className="px-3 text-xl">⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} className="w-full bg-transparent p-3 outline-none" placeholder="Lugar, evento, género o promoción"/></div><div className="flex gap-2 overflow-x-auto mt-4">{(["todo","eventos","lugares","promociones","favoritos"] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`shrink-0 rounded-full border px-4 py-2 text-sm capitalize ${tab === item ? "chip-active bg-neon2/10" : "border-line text-muted"}`}>{item}</button>)}</div></header>{message && <p className="rounded-xl border border-amber/30 bg-amber/10 p-3 text-sm text-amber">{message} {message.startsWith("Inicia") && <Link href="/login?next=/explorar" className="underline">Ingresar</Link>}</p>}
    {showEvents && <section><Title title="Eventos" count={events.length}/><div className="grid md:grid-cols-2 gap-4 mt-4">{events.map((item) => <article key={item.id} className="card p-5 relative"><button aria-label={favorite("event", item.id) ? "Quitar de favoritos" : "Guardar favorito"} onClick={() => void toggle("event", item.id)} className="absolute right-4 top-4 text-xl">{favorite("event", item.id) ? "♥" : "♡"}</button><Link href={`/eventos/${item.id}`} className="block pr-10"><p className="text-xs text-neon3">{lugarPorId(item.lugarId)?.nombre}</p><h2 className="text-xl font-bold mt-1">{item.nombre}</h2><p className="text-sm text-muted mt-2">{new Date(item.fechaISO).toLocaleString("es-CO", { dateStyle: "medium", timeStyle: "short" })}</p><p className="text-sm mt-3">{item.resumen}</p></Link></article>)}</div></section>}
    {showVenues && <section><div className="flex flex-wrap items-end justify-between gap-3"><Title title="Lugares" count={venues.length}/><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-xl border border-line bg-background px-4 py-2 text-sm"><option>Todas</option>{[...new Set(LUGARES.map((item) => item.categoria))].map((item) => <option key={item}>{item}</option>)}</select></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">{venues.map((item) => <article key={item.id} className="card p-5 relative"><button aria-label={favorite("venue", item.id) ? "Quitar de favoritos" : "Guardar favorito"} onClick={() => void toggle("venue", item.id)} className="absolute right-4 top-4 text-xl">{favorite("venue", item.id) ? "♥" : "♡"}</button><Link href={`/lugares/${item.id}`} className="block pr-8"><span className="text-3xl">{item.icono}</span><h2 className="text-xl font-bold mt-3">{item.nombre}</h2><p className="text-xs text-neon3">{item.zona} · {item.rangoPrecio}</p><p className="text-sm text-muted mt-3">{item.descripcion}</p></Link></article>)}</div></section>}
    {showPromotions && <section><Title title="Promociones" count={visiblePromotions.length}/><div className="grid md:grid-cols-2 gap-4 mt-4">{visiblePromotions.map((item) => <article key={item.id} className="card p-5 relative border-neon1/20"><button aria-label={favorite("promotion", item.id) ? "Quitar de favoritos" : "Guardar favorito"} onClick={() => void toggle("promotion", item.id)} className="absolute right-4 top-4 text-xl">{favorite("promotion", item.id) ? "♥" : "♡"}</button><p className="text-xs uppercase tracking-wider text-neon1">{item.venues?.name ?? item.events?.name}</p><h2 className="text-xl font-bold mt-2">{item.title}</h2><p className="text-sm text-muted mt-2">{item.description}</p><p className="text-xs text-muted mt-4">{item.terms}</p></article>)}{!visiblePromotions.length && <p className="card p-8 text-muted">No hay promociones disponibles con estos filtros.</p>}</div></section>}
  </main>;
}
function Title({ title, count }: { title: string; count: number }) { return <div><h2 className="text-2xl font-bold">{title}</h2><p className="text-xs text-muted">{count} resultados</p></div>; }
