"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useActiveVenue } from "@/lib/active-venue";
type Snapshot={venues:Array<{id:string;external_key?:string;name:string;city:string;active:boolean}>;collaborations:Array<{id:string;venue_id:string;status:string}>;promotions:Array<{id:string;venue_id:string;active:boolean}>;menuItems:Array<{id:string;venue_id:string;available:boolean}>;orders:Array<{id:string;venue_id:string;total_cop:number;status:string;customer_user_id?:string}>;reservations:Array<{id:string;venue_id:string;customer_user_id?:string}>};
export default function EstablishmentHome(){
  const[data,setData]=useState<Snapshot>();const[error,setError]=useState("");
  const{activeVenue}=useActiveVenue(data?.venues??[]);
  useEffect(()=>{let active=true;void fetch("/api/establishment",{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);if(active)setData(body)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Error")});return()=>{active=false}},[]);
  if(error)return<main className="p-8 text-danger">{error}</main>;if(!data)return<main className="p-8 text-muted">Preparando tu establecimiento…</main>;
  const venueId=activeVenue?.id;const orders=data.orders.filter(item=>item.venue_id===venueId);const reservations=data.reservations.filter(item=>item.venue_id===venueId);const delivered=orders.filter(item=>item.status==="delivered");const customers=new Set([...orders.map(item=>item.customer_user_id),...reservations.map(item=>item.customer_user_id)].filter(Boolean)).size;const collaborations=data.collaborations.filter(item=>item.venue_id===venueId);const promotions=data.promotions.filter(item=>item.venue_id===venueId);const menuItems=data.menuItems.filter(item=>item.venue_id===venueId);
  return<main className="flex-1 px-5 py-8 max-w-6xl mx-auto w-full space-y-7"><header className="card border-neon2/30 p-5"><p className="text-xs uppercase tracking-[.2em] text-neon2">NOCTA Business · Establecimiento</p><h1 className="text-3xl font-bold mt-2">Inicio</h1>{activeVenue&&<p className="mt-3 font-semibold text-neon2">● Administrando: {activeVenue.name} · {activeVenue.city}</p>}</header>{!data.venues.length&&<section className="card border-neon2/30 p-6"><h2 className="text-xl font-bold">Crea tu primer establecimiento</h2><p className="text-sm text-muted mt-2">Registra el lugar para habilitar menú, operación, promociones, clientes y equipo.</p><Link href="/admin/establecimientos" className="btn-neon inline-block rounded-xl px-5 py-3 mt-5">Crear establecimiento</Link></section>}<section className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Kpi title="Ventas" value={`$${delivered.reduce((sum,item)=>sum+item.total_cop,0).toLocaleString("es-CO")}`}/><Kpi title="Pedidos" value={orders.length}/><Kpi title="Reservas" value={reservations.length}/><Kpi title="Clientes" value={customers}/></section><section className="grid md:grid-cols-3 gap-4"><Card href="/admin/establecimientos" title="Establecimientos" detail={`${data.venues.length} ${data.venues.length===1?"sede registrada":"sedes registradas"}. Crea y administra tus lugares.`}/><Card href="/admin/operacion" title="Operación nocturna" detail="Pedidos, zonas, barra, mesa/VIP y cierre de esta sede."/><Card href="/admin/eventos" title="Solicitudes de eventos" detail={`${collaborations.filter(item=>item.status==="requested").length} solicitudes pendientes en esta sede.`}/><Card href="/admin/menu" title="Menú" detail={`${menuItems.filter(item=>item.available).length} productos disponibles en esta sede.`}/><Card href="/admin/promociones" title="Promociones" detail={`${promotions.filter(item=>item.active).length} promociones activas en esta sede.`}/><Card href="/reservas" title="Reservas" detail={`${reservations.length} reservas registradas en esta sede.`}/><Card href="/admin/clientes" title="Clientes" detail="Historial de reservas, pedidos y recurrencia de esta sede."/><Card href="/admin/equipo" title="Equipo" detail="Roles y acceso operativo por establecimiento."/><Card href="/admin/configuracion" title="Perfil y horarios" detail="Ubicación, contacto, categoría y horarios de esta sede."/></section></main>;
}
function Kpi({title,value}:{title:string;value:string|number}){return<div className="card p-5"><p className="text-xs text-muted">{title}</p><p className="text-2xl font-bold mt-1">{value}</p></div>}
function Card({href,title,detail}:{href:string;title:string;detail:string}){return<Link href={href} className="card p-5"><h2 className="font-bold text-lg">{title}</h2><p className="text-sm text-muted mt-2">{detail}</p><span className="block text-neon3 mt-4">Abrir →</span></Link>}
