import { NextRequest, NextResponse } from "next/server";
import { crearClienteSupabaseServidor } from "@/lib/supabase/server";

async function context() { const supabase = await crearClienteSupabaseServidor(); if (!supabase) return { error: NextResponse.json({ error: "Supabase no configurado" }, { status: 503 }) }; const { data: claims } = await supabase.auth.getClaims(); if (!claims?.claims?.sub) return { error: NextResponse.json({ error: "No autenticado" }, { status: 401 }) }; const { data: access, error } = await supabase.rpc("get_my_access_context"); const active = access?.activeContext as { organizationId?: string; role?: string } | undefined; if (error || active?.role !== "establishment" || !active.organizationId) return { error: NextResponse.json({ error: "Selecciona un contexto de establecimiento" }, { status: 409 }) }; return { supabase, organizationId: active.organizationId, userId: claims.claims.sub }; }

export async function GET() {
  const ctx = await context(); if (ctx.error) return ctx.error;
  const venues = await ctx.supabase!.from("venues").select("id,external_key,name,city,address,description,zone,latitude,longitude,phone,website,category,price_range,opening_hours,operational_settings,active").eq("organization_id", ctx.organizationId).order("name");
  if (venues.error) return NextResponse.json({ error: venues.error.message }, { status: 400 }); const ids = (venues.data ?? []).map((item) => item.id); if (!ids.length) return NextResponse.json({ organizationId: ctx.organizationId, venues: [], menuCategories: [], menuItems: [], promotions: [], reservations: [], orders: [], collaborations: [], team: [], customers: [], analytics: { revenue: 0, orders: 0, reservations: 0, customers: 0 } });
  const [categories, items, promotions, reservations, orders, collaborations, team] = await Promise.all([
    ctx.supabase!.from("venue_menu_categories").select("id,venue_id,name,sort_order,active").in("venue_id", ids).order("sort_order"),
    ctx.supabase!.from("venue_menu_items").select("id,venue_id,category_id,name,description,sku,price_cop,available,image_url").in("venue_id", ids).order("name"),
    ctx.supabase!.from("promotions").select("id,venue_id,title,description,terms,starts_at,ends_at,active").in("venue_id", ids).order("starts_at", { ascending: false }),
    ctx.supabase!.from("reservations").select("id,venue_id,customer_user_id,customer_name,phone,party_size,reserved_for,status,deposit_cop").in("venue_id", ids).order("reserved_for", { ascending: false }).limit(200),
    ctx.supabase!.from("orders").select("id,venue_id,customer_user_id,total_cop,status,created_at").in("venue_id", ids).order("created_at", { ascending: false }).limit(500),
    ctx.supabase!.from("event_venue_collaborations").select("id,venue_id,status,notes,created_at,events(id,name,starts_at,status)").in("venue_id", ids).order("created_at", { ascending: false }),
    ctx.supabase!.from("organization_memberships").select("id,user_id,status,profiles(full_name),organization_roles(context_role,role,scope_venue_id)").eq("organization_id", ctx.organizationId).order("created_at"),
  ]);
  const error = categories.error ?? items.error ?? promotions.error ?? reservations.error ?? orders.error ?? collaborations.error ?? team.error; if (error) return NextResponse.json({ error: error.message }, { status: 400 });
  const customerMap = new Map<string, { id: string; name: string; phone?: string | null; reservations: number; orders: number; spend: number; lastActivity: string }>();
  for (const row of reservations.data ?? []) { const key = row.customer_user_id ?? `phone:${row.phone ?? row.customer_name}`; const current = customerMap.get(key) ?? { id: key, name: row.customer_name, phone: row.phone, reservations: 0, orders: 0, spend: 0, lastActivity: row.reserved_for }; current.reservations++; if (row.reserved_for > current.lastActivity) current.lastActivity = row.reserved_for; customerMap.set(key, current); }
  for (const row of orders.data ?? []) if (row.customer_user_id) { const current = customerMap.get(row.customer_user_id) ?? { id: row.customer_user_id, name: "Cliente NOCTA", reservations: 0, orders: 0, spend: 0, lastActivity: row.created_at }; current.orders++; if (row.status === "delivered") current.spend += row.total_cop; if (row.created_at > current.lastActivity) current.lastActivity = row.created_at; customerMap.set(row.customer_user_id, current); }
  const delivered = (orders.data ?? []).filter((item) => item.status === "delivered");
  return NextResponse.json({ organizationId: ctx.organizationId, venues: venues.data, menuCategories: categories.data ?? [], menuItems: items.data ?? [], promotions: promotions.data ?? [], reservations: reservations.data ?? [], orders: orders.data ?? [], collaborations: collaborations.data ?? [], team: team.data ?? [], customers: [...customerMap.values()].sort((a, b) => b.lastActivity.localeCompare(a.lastActivity)), analytics: { revenue: delivered.reduce((sum, item) => sum + item.total_cop, 0), orders: orders.data?.length ?? 0, reservations: reservations.data?.length ?? 0, customers: customerMap.size } });
}

export async function PATCH(request: NextRequest) { const ctx = await context(); if (ctx.error) return ctx.error; const body = await request.json() as Record<string, unknown>; if (!body.venueId) return NextResponse.json({ error: "Establecimiento requerido" }, { status: 400 }); const allowed = ["name","city","address","description","zone","latitude","longitude","phone","website","category","price_range","opening_hours","operational_settings","active"]; const update = Object.fromEntries(Object.entries(body).filter(([key]) => allowed.includes(key))); const { error } = await ctx.supabase!.from("venues").update({ ...update, updated_at: new Date().toISOString() }).eq("id", body.venueId).eq("organization_id", ctx.organizationId); return error ? NextResponse.json({ error: error.message }, { status: 400 }) : NextResponse.json({ ok: true }); }

export async function POST(request: NextRequest) { const ctx = await context(); if (ctx.error) return ctx.error; const body = await request.json() as Record<string, unknown>; const action = String(body.action ?? ""); let result: { error: { message: string } | null }; if (action === "category") result = await ctx.supabase!.from("venue_menu_categories").insert({ venue_id: body.venueId, name: body.name, sort_order: body.sortOrder ?? 0 }); else if (action === "item") result = await ctx.supabase!.from("venue_menu_items").insert({ venue_id: body.venueId, category_id: body.categoryId || null, name: body.name, description: body.description ?? "", sku: body.sku || null, price_cop: body.priceCop, available: true }); else if (action === "promotion") result = await ctx.supabase!.from("promotions").insert({ venue_id: body.venueId, title: body.title, description: body.description ?? "", terms: body.terms ?? "", starts_at: body.startsAt, ends_at: body.endsAt, created_by: ctx.userId }); else return NextResponse.json({ error: "Acción inválida" }, { status: 400 }); return result.error ? NextResponse.json({ error: result.error.message }, { status: 400 }) : NextResponse.json({ ok: true }, { status: 201 }); }

export async function DELETE(request: NextRequest) { const ctx = await context(); if (ctx.error) return ctx.error; const body = await request.json() as { type?: "item" | "category"; id?: string }; if (!body.id) return NextResponse.json({ error: "Registro requerido" }, { status: 400 }); const table = body.type === "category" ? "venue_menu_categories" : "venue_menu_items"; const { error } = await ctx.supabase!.from(table).delete().eq("id", body.id); return error ? NextResponse.json({ error: error.message }, { status: 400 }) : NextResponse.json({ ok: true }); }
