import { NextRequest, NextResponse } from "next/server";
import { crearClienteSupabaseServidor } from "@/lib/supabase/server";

async function context() { const supabase = await crearClienteSupabaseServidor(); if (!supabase) return { error: NextResponse.json({ error: "Supabase no configurado" }, { status: 503 }) }; const { data: claims } = await supabase.auth.getClaims(); if (!claims?.claims?.sub) return { error: NextResponse.json({ error: "No autenticado" }, { status: 401 }) }; const { data: access, error } = await supabase.rpc("get_my_access_context"); const active = access?.activeContext as { organizationId?: string; role?: string } | undefined; if (error || active?.role !== "establishment" || !active.organizationId) return { error: NextResponse.json({ error: "Selecciona un contexto de establecimiento" }, { status: 409 }) }; return { supabase, organizationId: active.organizationId, userId: claims.claims.sub }; }

export async function GET() {
  const ctx = await context(); if (ctx.error) return ctx.error;
  const venueCategoryCatalog=await ctx.supabase!.from("venue_categories").select("id,slug,name,description,sort_order").eq("active",true).order("sort_order").order("name");if(venueCategoryCatalog.error)return NextResponse.json({error:venueCategoryCatalog.error.message},{status:400});
  const venues = await ctx.supabase!.from("venues").select("id,external_key,name,city,address,description,zone,latitude,longitude,phone,website,category,price_range,opening_hours,operational_settings,active").eq("organization_id", ctx.organizationId).order("name");
  if (venues.error) return NextResponse.json({ error: venues.error.message }, { status: 400 }); const ids = (venues.data ?? []).map((item) => item.id); if (!ids.length) return NextResponse.json({ organizationId: ctx.organizationId, venues: [], venueCategories:venueCategoryCatalog.data??[],venueCategoryAssignments:[], menuCategories: [], menuItems: [], promotions: [], reservations: [], orders: [], collaborations: [], team: [], customers: [], analytics: { revenue: 0, orders: 0, reservations: 0, customers: 0 } });
  const [categories, items, promotions, reservations, orders, collaborations, team,venueCategoryAssignments] = await Promise.all([
    ctx.supabase!.from("venue_menu_categories").select("id,venue_id,name,sort_order,active").in("venue_id", ids).order("sort_order"),
    ctx.supabase!.from("venue_menu_items").select("id,venue_id,category_id,name,description,sku,price_cop,available,image_url").in("venue_id", ids).order("name"),
    ctx.supabase!.from("promotions").select("id,venue_id,title,description,terms,starts_at,ends_at,active").in("venue_id", ids).order("starts_at", { ascending: false }),
    ctx.supabase!.from("reservations").select("id,venue_id,customer_user_id,customer_name,phone,party_size,reserved_for,status,deposit_cop").in("venue_id", ids).order("reserved_for", { ascending: false }).limit(200),
    ctx.supabase!.from("orders").select("id,venue_id,customer_user_id,total_cop,status,created_at").in("venue_id", ids).order("created_at", { ascending: false }).limit(500),
    ctx.supabase!.from("event_venue_collaborations").select("id,venue_id,status,notes,created_at,events(id,name,starts_at,status)").in("venue_id", ids).order("created_at", { ascending: false }),
    ctx.supabase!.from("organization_memberships").select("id,user_id,status,profiles(full_name),organization_roles(context_role,role,scope_venue_id)").eq("organization_id", ctx.organizationId).order("created_at"),
    ctx.supabase!.from("venue_category_assignments").select("venue_id,category_id").in("venue_id",ids),
  ]);
  const error = categories.error ?? items.error ?? promotions.error ?? reservations.error ?? orders.error ?? collaborations.error ?? team.error??venueCategoryAssignments.error; if (error) return NextResponse.json({ error: error.message }, { status: 400 });
  const customerMap = new Map<string, { id: string; name: string; phone?: string | null; reservations: number; orders: number; spend: number; lastActivity: string; venueIds: string[]; venueStats: Record<string,{ reservations: number; orders: number; spend: number }> }>();
  for (const row of reservations.data ?? []) { const key = row.customer_user_id ?? `phone:${row.phone ?? row.customer_name}`; const current = customerMap.get(key) ?? { id: key, name: row.customer_name, phone: row.phone, reservations: 0, orders: 0, spend: 0, lastActivity: row.reserved_for, venueIds: [] as string[], venueStats: {} as Record<string,{reservations:number;orders:number;spend:number}> }; current.reservations++; current.venueStats[row.venue_id] ??= {reservations:0,orders:0,spend:0}; current.venueStats[row.venue_id].reservations++; if (!current.venueIds.includes(row.venue_id)) current.venueIds.push(row.venue_id); if (row.reserved_for > current.lastActivity) current.lastActivity = row.reserved_for; customerMap.set(key, current); }
  for (const row of orders.data ?? []) if (row.customer_user_id) { const current = customerMap.get(row.customer_user_id) ?? { id: row.customer_user_id, name: "Cliente NOCTA", reservations: 0, orders: 0, spend: 0, lastActivity: row.created_at, venueIds: [] as string[], venueStats: {} as Record<string,{reservations:number;orders:number;spend:number}> }; current.orders++; current.venueStats[row.venue_id] ??= {reservations:0,orders:0,spend:0}; current.venueStats[row.venue_id].orders++; if (!current.venueIds.includes(row.venue_id)) current.venueIds.push(row.venue_id); if (row.status === "delivered") { current.spend += row.total_cop; current.venueStats[row.venue_id].spend += row.total_cop; } if (row.created_at > current.lastActivity) current.lastActivity = row.created_at; customerMap.set(row.customer_user_id, current); }
  const delivered = (orders.data ?? []).filter((item) => item.status === "delivered");
  return NextResponse.json({ organizationId: ctx.organizationId, venues: venues.data,venueCategories:venueCategoryCatalog.data??[],venueCategoryAssignments:venueCategoryAssignments.data??[], menuCategories: categories.data ?? [], menuItems: items.data ?? [], promotions: promotions.data ?? [], reservations: reservations.data ?? [], orders: orders.data ?? [], collaborations: collaborations.data ?? [], team: team.data ?? [], customers: [...customerMap.values()].sort((a, b) => b.lastActivity.localeCompare(a.lastActivity)), analytics: { revenue: delivered.reduce((sum, item) => sum + item.total_cop, 0), orders: orders.data?.length ?? 0, reservations: reservations.data?.length ?? 0, customers: customerMap.size } });
}

export async function PATCH(request: NextRequest) { const ctx = await context(); if (ctx.error) return ctx.error; const body = await request.json() as Record<string, unknown>; if(body.action==="venue_categories"){if(!body.venueId||!Array.isArray(body.categoryIds))return NextResponse.json({error:"Establecimiento y categorías requeridos"},{status:400});const{error}=await ctx.supabase!.rpc("set_venue_categories",{target_venue:body.venueId,category_ids:body.categoryIds});return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({ok:true});} if (body.action === "promotion_status") { if (!body.id || typeof body.active !== "boolean") return NextResponse.json({ error: "Promoción y estado requeridos" }, { status: 400 }); const venues = await ctx.supabase!.from("venues").select("id").eq("organization_id", ctx.organizationId); if (venues.error) return NextResponse.json({ error: venues.error.message }, { status: 400 }); const venueIds=(venues.data??[]).map(item=>item.id); if(!venueIds.length)return NextResponse.json({error:"La organización no tiene establecimientos"},{status:409}); const {data,error}=await ctx.supabase!.from("promotions").update({active:body.active,updated_at:new Date().toISOString()}).eq("id",body.id).in("venue_id",venueIds).select("id").maybeSingle(); if(error)return NextResponse.json({error:error.message},{status:400});return data?NextResponse.json({ok:true}):NextResponse.json({error:"Promoción no encontrada en el establecimiento activo"},{status:404}); } if (!body.venueId) return NextResponse.json({ error: "Establecimiento requerido" }, { status: 400 }); const allowed = ["name","city","address","description","zone","latitude","longitude","phone","website","price_range","opening_hours","operational_settings","active"]; const update = Object.fromEntries(Object.entries(body).filter(([key]) => allowed.includes(key))); if(!Object.keys(update).length)return NextResponse.json({error:"No hay cambios válidos"},{status:400});const {data,error} = await ctx.supabase!.from("venues").update({ ...update, updated_at: new Date().toISOString() }).eq("id", body.venueId).eq("organization_id", ctx.organizationId).select("id").maybeSingle(); if(error)return NextResponse.json({error:error.message},{status:400});if(!data)return NextResponse.json({error:"Establecimiento no encontrado en el contexto activo"},{status:404});if(Array.isArray(body.categoryIds)){const categoryResult=await ctx.supabase!.rpc("set_venue_categories",{target_venue:body.venueId,category_ids:body.categoryIds});if(categoryResult.error)return NextResponse.json({error:categoryResult.error.message},{status:400});}return NextResponse.json({ok:true}); }

export async function POST(request: NextRequest) { const ctx = await context(); if (ctx.error) return ctx.error; const body = await request.json() as Record<string, unknown>; const action = String(body.action ?? ""); if (action === "venue") { const name=String(body.name??"").trim();const city=String(body.city??"").trim();if(name.length<2||city.length<2)return NextResponse.json({error:"Nombre y ciudad son obligatorios"},{status:400});const {data,error}=await ctx.supabase!.rpc("create_organization_venue",{target_organization:ctx.organizationId,venue_name:name,venue_city:city,venue_address:String(body.address??""),venue_category:null});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true,id:data},{status:201}); } let result: { error: { message: string } | null }; if (action === "category") result = await ctx.supabase!.from("venue_menu_categories").insert({ venue_id: body.venueId, name: body.name, sort_order: body.sortOrder ?? 0 }); else if (action === "item") result = await ctx.supabase!.from("venue_menu_items").insert({ venue_id: body.venueId, category_id: body.categoryId || null, name: body.name, description: body.description ?? "", sku: body.sku || null, price_cop: body.priceCop, available: true }); else if (action === "promotion") { const title=String(body.title??"").trim();const description=String(body.description??"").trim();const terms=String(body.terms??"").trim();const startsAt=new Date(String(body.startsAt??""));const endsAt=new Date(String(body.endsAt??""));if(!body.venueId||title.length<4||description.length<10||terms.length<5||Number.isNaN(startsAt.getTime())||Number.isNaN(endsAt.getTime())||endsAt<=startsAt)return NextResponse.json({error:"Completa título, descripción, condiciones y una vigencia válida"},{status:400});const venue=await ctx.supabase!.from("venues").select("id").eq("id",body.venueId).eq("organization_id",ctx.organizationId).maybeSingle();if(venue.error||!venue.data)return NextResponse.json({error:"El establecimiento no pertenece al contexto activo"},{status:403});result = await ctx.supabase!.from("promotions").insert({ venue_id: body.venueId, title, description, terms, starts_at: startsAt.toISOString(), ends_at: endsAt.toISOString(), active:true, created_by: ctx.userId }); } else return NextResponse.json({ error: "Acción inválida" }, { status: 400 }); return result.error ? NextResponse.json({ error: result.error.message }, { status: 400 }) : NextResponse.json({ ok: true }, { status: 201 }); }

export async function DELETE(request: NextRequest) { const ctx = await context(); if (ctx.error) return ctx.error; const body = await request.json() as { type?: "item" | "category"; id?: string }; if (!body.id) return NextResponse.json({ error: "Registro requerido" }, { status: 400 }); const venues=await ctx.supabase!.from("venues").select("id").eq("organization_id",ctx.organizationId);if(venues.error)return NextResponse.json({error:venues.error.message},{status:400});const venueIds=(venues.data??[]).map(item=>item.id);if(!venueIds.length)return NextResponse.json({error:"La organización no tiene establecimientos"},{status:409});const table = body.type === "category" ? "venue_menu_categories" : "venue_menu_items"; const {data,error} = await ctx.supabase!.from(table).delete().eq("id", body.id).in("venue_id",venueIds).select("id").maybeSingle(); if(error)return NextResponse.json({error:error.message},{status:400});return data?NextResponse.json({ok:true}):NextResponse.json({error:"Registro no encontrado en el establecimiento activo"},{status:404}); }
