"use client";
import Link from "next/link";
import {useMemo}from"react";
import {Logo}from"@/components/ui";
import {CerrarSesionCliente}from"@/components/cerrar-sesion";
import {RestablecerDemo}from"@/components/restablecer-demo";
import {formatearFecha}from"@/lib/discovery";
import {useCatalogoNocta}from"@/lib/cloud-catalog";
import {useExperienciasSociales}from"@/lib/social-events";

export default function InicioConsumidor(){const catalogo=useCatalogoNocta();const experiencias=useExperienciasSociales().filter(item=>item.estado==="open");const recomendados=useMemo(()=>catalogo.eventos.slice().sort((a,b)=>Number(Boolean(b.destacado))-Number(Boolean(a.destacado))||new Date(a.fechaISO).getTime()-new Date(b.fechaISO).getTime()).slice(0,2),[catalogo.eventos]);const lugares=catalogo.lugares.slice(0,3);const hora=new Date().getHours();const saludo=hora<12?"Buenos días":hora<19?"Buenas tardes":"Buenas noches";return <main className="flex-1 pb-12"><header className="sticky top-0 z-20 border-b border-line bg-background/85 backdrop-blur-xl"><div className="max-w-5xl mx-auto px-5 py-4 flex items-center justify-between"><Logo size="text-3xl"/><CerrarSesionCliente/></div></header><div className="max-w-5xl mx-auto px-5 space-y-10">
  <section className="pt-10 md:pt-16"><p className="text-sm font-semibold text-neon3">{saludo} · Cartagena</p><h1 className="text-4xl md:text-6xl font-bold tracking-tight mt-2">¿Qué hacemos hoy?</h1><p className="text-muted mt-3 md:text-lg max-w-2xl">Una selección corta para decidir rápido. Si quieres comparar todo, entra a Explorar.</p><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-7"><Shortcut href="/explorar" icon="⌖" title="Explorar todo" detail="Lugares y promociones"/><Shortcut href="/eventos" icon="◇" title="Ver agenda" detail="Por día y disponibilidad"/><Shortcut href="/mis-planes" icon="▣" title="Mis planes" detail="Entradas y reservas"/><Shortcut href="/mi-nocta" icon="✦" title="Mi NOCTA" detail="Puntos y beneficios"/></div></section>
  <section><Heading eyebrow="Para esta noche" title="Selección NOCTA" action="Ver agenda completa" href="/eventos"/><div className="grid md:grid-cols-2 gap-4 mt-4">{recomendados.map(evento=>{const lugar=catalogo.lugares.find(item=>item.id===evento.lugarId);return <Link key={evento.id} href={`/eventos/${evento.id}`} className="card overflow-hidden group hover:border-neon1/60"><div className="h-40 p-5 flex flex-col justify-between relative overflow-hidden" style={{background:`linear-gradient(135deg,${evento.color}55,#100e1c 75%)`}}><span className="self-start rounded-full bg-black/40 px-3 py-1 text-xs">{evento.disponibilidad==="ultimos"?"Últimas entradas":evento.disponibilidad==="lista"?"Acceso por lista":"Disponible"}</span><div><p className="text-sm text-white/70">{lugar?.nombre}</p><h2 className="text-2xl font-bold">{evento.nombre}</h2></div></div><div className="p-5 flex justify-between gap-4"><span className="text-sm text-neon3 capitalize">{formatearFecha(evento.fechaISO)}</span><b className="text-sm">{evento.precioDesde?`Desde $${evento.precioDesde.toLocaleString("es-CO")}`:"Entrada libre"}</b></div></Link>})}</div></section>
  {experiencias[0]&&<section><Heading eyebrow="Conecta en persona" title="Una experiencia diferente" action="Explorar experiencias" href="/explorar"/><Link href={`/experiencias/${experiencias[0].id}`} className="card mt-4 p-6 block border-neon3/25 hover:border-neon3/60"><p className="text-xs uppercase tracking-wider text-neon3">{experiencias[0].tipo} · {experiencias[0].lugarNombre}</p><h2 className="text-2xl font-bold mt-2">{experiencias[0].nombre}</h2><p className="text-sm text-muted mt-2 max-w-2xl">{experiencias[0].descripcion}</p><p className="text-sm text-neon2 mt-4">{experiencias[0].participantes.length}/{experiencias[0].capacidad} confirmados →</p></Link></section>}
  <section><Heading eyebrow="Cerca de ti" title="Lugares recomendados" action="Buscar lugares" href="/explorar"/><div className="grid md:grid-cols-3 gap-4 mt-4">{lugares.map(lugar=><Link key={lugar.id} href={`/lugares/${lugar.id}`} className="card p-5 hover:border-neon1/60"><span className="text-3xl">{lugar.icono}</span><h2 className="font-bold text-lg mt-3">{lugar.nombre}</h2><p className="text-xs text-neon3">{lugar.zona} · {lugar.rangoPrecio}</p><p className="text-sm text-muted mt-2 line-clamp-2">{lugar.descripcion}</p></Link>)}</div></section>
  {process.env.NODE_ENV!=="production"&&<RestablecerDemo/>}
</div></main>}
function Shortcut({href,icon,title,detail}:{href:string;icon:string;title:string;detail:string}){return <Link href={href} className="card p-4 hover:border-neon2/50"><span className="text-2xl">{icon}</span><b className="block mt-3 text-sm">{title}</b><span className="block text-xs text-muted mt-1">{detail}</span></Link>}
function Heading({eyebrow,title,action,href}:{eyebrow:string;title:string;action:string;href:string}){return <div className="flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-neon2">{eyebrow}</p><h2 className="text-2xl font-bold mt-1">{title}</h2></div><Link href={href} className="text-sm text-neon3 text-right">{action} →</Link></div>}
