"use client";

import { FormEvent, useMemo, useState } from "react";
import { ORGANIZATION_ROLE_LABELS, type OrganizationRole } from "@/lib/auth/roles";

type Role = { context_role: string; role: string; scope_venue_id?: string | null };
type Member = { id: string; user_id: string; status: string; profiles?: { full_name?: string }; organization_roles?: Role[] };
const ASSIGNABLE: OrganizationRole[] = ["establishment_admin", "bar", "waiter", "cashier"];
const AREA: Record<string,{label:string;description:string;access:string;icon:string}>={establishment_admin:{label:"Administración",description:"Configura la sede, menú, promociones, eventos, equipo y analítica.",access:"Panel completo de establecimiento",icon:"⚙"},bar:{label:"Barra y cocina",description:"Prepara y despacha pedidos por estación: barra, cocina, café u otras.",access:"Cola de preparación /barra",icon:"◉"},waiter:{label:"Meseros",description:"Recibe pedidos listos y gestiona entregas por zona, mesa o VIP.",access:"Consola de entregas /mesero",icon:"◇"},cashier:{label:"Caja",description:"Confirma cobros en efectivo o datáfono y apoya el despacho.",access:"Cobro y preparación /barra",icon:"$"}};

export function EstablishmentTeam({ organizationId, venueId, venueName, members }: { organizationId: string; venueId: string; venueName: string; members: Member[] }) {
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [team, setTeam] = useState(members);
  const visible = useMemo(() => team.map(member => ({ ...member, roles: (member.organization_roles ?? []).filter(role => role.context_role === "establishment" && (!role.scope_venue_id || role.scope_venue_id === venueId)) })).filter(member => member.roles.length), [team, venueId]);
  const counts=useMemo(()=>Object.fromEntries(ASSIGNABLE.map(role=>[role,visible.filter(member=>member.roles.some(item=>item.role===role)).length])),[visible]);
  async function refresh() { const response = await fetch("/api/establishment", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "No fue posible actualizar el listado."); setTeam(result.team ?? []); }
  async function request(method: "POST" | "DELETE", body: Record<string, unknown>) { setBusy(true); setError(""); setMessage(""); const response = await fetch("/api/organizations", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setBusy(false); setError(result.error ?? "No fue posible actualizar el equipo."); return false; } try { await refresh(); setMessage(method === "POST" ? "Acceso asignado correctamente." : "Acceso retirado correctamente."); } catch (reason) { setError(reason instanceof Error ? reason.message : "El acceso cambió, pero no fue posible actualizar la lista."); } finally { setBusy(false); } return true; }
  async function invite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); if (await request("POST", { action: "set_member_by_email", organizationId, userEmail: values.get("email"), context: "establishment", role: values.get("role"), venueId })) form.reset(); }
  return <div className="space-y-5">
    <section className="card border-neon2/30 p-5"><p className="text-xs uppercase tracking-[.18em] text-neon2">Sede activa</p><h2 className="mt-1 text-xl font-bold">{venueName}</h2><p className="mt-1 text-sm text-muted">Los accesos creados aquí aplican únicamente a esta sede.</p></section>
    {error && <p role="alert" className="rounded-xl border border-danger/30 bg-danger/10 p-3 text-danger">{error}</p>}{message && <p role="status" className="rounded-xl border border-lime/30 bg-lime/10 p-3 text-lime">{message}</p>}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{ASSIGNABLE.map(role=><div key={role} className="card p-4"><div className="flex items-center justify-between"><span className="text-xl text-neon2">{AREA[role].icon}</span><b className="text-xl">{counts[role]??0}</b></div><p className="mt-2 text-sm font-semibold">{AREA[role].label}</p><p className="mt-1 text-xs text-muted">{AREA[role].description}</p></div>)}</section>
    <div className="grid gap-5 lg:grid-cols-[minmax(280px,1fr)_2fr]">
      <form onSubmit={invite} className="card h-fit space-y-3 p-5"><div><h2 className="font-bold">Agregar al equipo</h2><p className="mt-1 text-xs text-muted">La persona debe tener una cuenta NOCTA. El acceso quedará limitado a {venueName}.</p></div><label className="block text-xs text-muted">Correo electrónico<input name="email" type="email" autoComplete="email" required className="entrada mt-1" placeholder="persona@correo.com"/></label><label className="block text-xs text-muted">Área y responsabilidad<select name="role" className="entrada mt-1 bg-background">{ASSIGNABLE.map(role => <option key={role} value={role}>{AREA[role].label}</option>)}</select></label><div className="space-y-2 rounded-xl bg-surface2 p-3">{ASSIGNABLE.map(role=><p key={role} className="text-xs"><b>{AREA[role].label}:</b> <span className="text-muted">{AREA[role].access}</span></p>)}</div><button disabled={busy} className="btn-neon w-full rounded-xl p-3 disabled:opacity-50">{busy ? "Asignando…" : "Asignar acceso a la sede"}</button></form>
      <section className="space-y-3"><div><h2 className="font-bold">Equipo con acceso</h2><p className="text-sm text-muted">Responsables generales y operadores de {venueName}.</p></div>{visible.map(member => <article key={member.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{member.profiles?.full_name || "Usuario NOCTA"}</h3><p className="text-xs text-muted">{member.status === "active" ? "Cuenta activa" : member.status}</p></div><span className="rounded-full bg-lime/10 px-2.5 py-1 text-xs text-lime">{member.roles.length} acceso(s)</span></div><div className="mt-3 space-y-2">{member.roles.map((role, index) => {const area=AREA[role.role]??{label:ORGANIZATION_ROLE_LABELS[role.role as OrganizationRole]??role.role,description:"Acceso empresarial",access:"Panel empresarial",icon:"•"};return <div key={`${role.role}-${role.scope_venue_id ?? "all"}-${index}`} className="flex items-center justify-between gap-3 rounded-xl border border-line px-3 py-3"><span className="text-sm"><b>{area.icon} {area.label}</b><small className="block text-muted">{area.access} · {role.scope_venue_id ? "solo esta sede" : "todas las sedes"}</small></span><button type="button" disabled={busy} onClick={() => { if (window.confirm(`¿Retirar este acceso de ${member.profiles?.full_name || "la persona"}?`)) void request("DELETE", { organizationId, userId: member.user_id, context: "establishment", role: role.role, venueId: role.scope_venue_id || undefined }); }} className="rounded-lg border border-danger/30 px-3 py-2 text-xs text-danger disabled:opacity-40">Retirar</button></div>})}</div></article>)}{!visible.length && <div className="card p-8 text-center"><p className="font-semibold">Aún no hay equipo asignado</p><p className="mt-1 text-sm text-muted">Agrega administración, barra/cocina, meseros o caja para esta sede.</p></div>}</section>
    </div>
  </div>;
}
