"use client";

import { useState } from "react";

type Category={id:string;name:string};
type Item={id:string;category_id?:string;name:string;description:string;price_cop:number;available:boolean};

export function VenueMenuProducts({items,categories,onUpdate,onDelete}:{items:Item[];categories:Category[];onUpdate:(body:Record<string,unknown>)=>Promise<boolean>;onDelete:(id:string,name:string)=>void}){
  const[editing,setEditing]=useState<string>();const[price,setPrice]=useState("");const[busy,setBusy]=useState<string>();
  async function update(item:Item,changes:Record<string,unknown>){setBusy(item.id);const ok=await onUpdate({action:"menu_item",id:item.id,...changes});setBusy(undefined);if(ok)setEditing(undefined)}
  return <section className="card overflow-hidden"><div className="border-b border-line p-4"><h2 className="font-bold">Carta de productos</h2><p className="text-xs text-muted mt-1">Edita precios y disponibilidad en vivo para la sede activa.</p></div>{items.map(item=><article key={item.id} className="flex flex-col gap-3 border-b border-line p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><b>{item.name}</b><span className="block text-xs text-muted">{item.description}</span><span className="block text-xs text-neon3">{categories.find(category=>category.id===item.category_id)?.name??"Sin categoría"}</span></div><div className="flex flex-wrap items-center gap-2">{editing===item.id?<><input value={price} onChange={event=>setPrice(event.target.value.replace(/\D/g,""))} inputMode="numeric" autoFocus className="w-28 rounded-xl border border-line bg-background px-3 py-2 text-sm outline-none focus:border-neon2"/><button type="button" disabled={busy===item.id||Number(price)<=0} onClick={()=>void update(item,{priceCop:Number(price)})} className="rounded-xl border border-lime/40 px-3 py-2 text-sm font-bold text-lime disabled:opacity-40">✓</button><button type="button" onClick={()=>setEditing(undefined)} className="px-2 text-muted">×</button></>:<button type="button" onClick={()=>{setEditing(item.id);setPrice(String(item.price_cop))}} className="rounded-xl border border-neon2/30 px-3 py-2 text-sm font-bold text-neon2">${item.price_cop.toLocaleString("es-CO")} ✎</button>}<button type="button" disabled={busy===item.id} onClick={()=>void update(item,{available:!item.available})} className={`rounded-xl border px-3 py-2 text-xs font-semibold disabled:opacity-40 ${item.available?"border-lime/40 text-lime":"border-danger/40 text-danger"}`}>{item.available?"Disponible":"Agotado"}</button><button type="button" onClick={()=>onDelete(item.id,item.name)} className="px-2 py-2 text-xs text-danger">Eliminar</button></div></article>)}{!items.length&&<p className="p-8 text-muted">Agrega el primer producto.</p>}</section>;
}
