"use client";

import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { eventoPorId, lugarPorId } from "@/lib/discovery";
import { crearReserva, OPCIONES_RESERVA, reservasDisponibles, useReservas, type TipoReserva } from "@/lib/reservations";

export default function ReservarEvento() {
  const { id } = useParams<{id:string}>(); const router = useRouter(); const evento = eventoPorId(id); const lugar = evento ? lugarPorId(evento.lugarId) : undefined;
  const reservas = useReservas(); const [tipoId,setTipoId]=useState<TipoReserva>("mesa"); const tipo=OPCIONES_RESERVA.find(o=>o.id===tipoId)!;
  const [personas,setPersonas]=useState(2); const [titular,setTitular]=useState(""); const [telefono,setTelefono]=useState(""); const [email,setEmail]=useState(""); const [ocasion,setOcasion]=useState(""); const [notas,setNotas]=useState(""); const [error,setError]=useState("");
  if(!evento||!lugar) return <main className="p-8 text-muted">Evento no disponible.</main>;
  const disponible=reservasDisponibles(id,tipo,reservas)>0; const valido=disponible&&personas>=1&&personas<=tipo.capacidad&&titular.trim()&&telefono.trim()&&email.includes("@");
  async function confirmar(){ try{const respuesta=await fetch("/api/reservations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventKey:id,partySize:personas,customerName:titular,phone:telefono,email,zoneName:tipo.nombre,depositCop:tipo.anticipo,notes:[ocasion,notas].filter(Boolean).join(" · ")})});const remoto=await respuesta.json() as {id?:string;token?:string;error?:string};if(!respuesta.ok||!remoto.id||!remoto.token)throw new Error(remoto.error??"No pudimos registrar la reserva."); const reserva=crearReserva({eventoId:id,tipoId,personas,titular,telefono,email,ocasion,notas,emitida:{id:remoto.id,token:remoto.token}}); router.push(`/mis-reservas/${reserva.id}`); }catch(e){setError(e instanceof Error?e.message:"No pudimos crear la reserva.");} }
  return <main className="flex-1 px-5 py-8 max-w-lg mx-auto w-full space-y-6"><button onClick={()=>router.back()} className="text-sm text-muted">← Volver al evento</button><header><p className="text-neon3 text-sm font-semibold">{lugar.nombre}</p><h1 className="text-3xl font-bold mt-1">Reserva tu espacio</h1><p className="text-muted mt-2">{evento.nombre} · solicitud sujeta a confirmación del establecimiento.</p></header><section className="space-y-3">{OPCIONES_RESERVA.map(o=>{const quedan=reservasDisponibles(id,o,reservas);return <button key={o.id} disabled={!quedan} onClick={()=>{setTipoId(o.id);setPersonas(Math.min(personas,o.capacidad));}} className={`card w-full p-4 text-left disabled:opacity-40 ${tipoId===o.id?"chip-active":""}`}><div className="flex justify-between gap-4"><span><b>{o.nombre}</b><span className="block text-xs text-muted mt-1">{o.descripcion}</span></span><span className="text-right shrink-0"><b>Hasta {o.capacidad}</b><span className="block text-[10px] text-muted">{quedan} disponibles</span></span></div><div className="grid grid-cols-2 gap-2 mt-3 text-xs"><span>Consumo mín. ${o.consumoMinimo.toLocaleString("es-CO")}</span><span className="text-right text-neon3">Anticipo ${o.anticipo.toLocaleString("es-CO")}</span></div></button>})}</section><section className="card p-5 space-y-3"><label className="text-sm">Número de personas<input type="number" min={1} max={tipo.capacidad} value={personas} onChange={e=>setPersonas(Number(e.target.value))} className="entrada"/></label><input value={titular} onChange={e=>setTitular(e.target.value)} className="entrada" placeholder="Nombre del responsable"/><input value={telefono} onChange={e=>setTelefono(e.target.value)} className="entrada" placeholder="WhatsApp"/><input value={email} onChange={e=>setEmail(e.target.value)} className="entrada" type="email" placeholder="Correo"/><select value={ocasion} onChange={e=>setOcasion(e.target.value)} className="entrada"><option value="">Ocasión (opcional)</option><option>Cumpleaños</option><option>Celebración</option><option>Empresa</option><option>Salida con amigos</option></select><textarea value={notas} onChange={e=>setNotas(e.target.value)} className="entrada min-h-20" placeholder="Solicitud especial (opcional)"/></section><section className="card p-5"><div className="flex justify-between"><span>Anticipo al confirmar</span><b className="text-neon2">${tipo.anticipo.toLocaleString("es-CO")}</b></div><p className="text-xs text-muted mt-2">El anticipo se descuenta del consumo mínimo. En este MVP el cobro se registra al confirmar la reserva.</p></section>{error&&<p className="rounded-xl border border-danger/40 bg-danger/10 p-3 text-danger text-sm">{error}</p>}<button disabled={!valido} onClick={confirmar} className="btn-neon w-full rounded-2xl p-4 font-bold disabled:opacity-40">Solicitar reserva</button></main>;
}
