"use client";

import { useEffect, useMemo, useState, useSyncExternalStore } from "react";

export interface TipoEntradaPromotor { id:string; nombre:string; precio:number; descripcion:string; cupo:number }
export interface EventoPromotorNocta {
  id:string; nombre:string; resumen:string; descripcion:string; lugarNombre:string; ciudad:string; zona:string;
  fechaISO:string; horaFin:string; generos:string[]; edadMinima:number; dressCode:string; color:string;
  promotor:string; estado:"borrador"|"publicado"|"cerrado"; tiposEntrada:TipoEntradaPromotor[];
  reservasActivas:boolean; listasActivas:boolean; capacidad:number; creadoEn:number;
}
const KEY="nocta-promoter-events-v1";const EVENT="nocta-promoter-events-change";
function snapshot(){return typeof window==="undefined"?"[]":localStorage.getItem(KEY)??"[]"}
function parsear(raw:string):EventoPromotorNocta[]{try{return JSON.parse(raw) as EventoPromotorNocta[]}catch{return[]}}
function guardar(eventos:EventoPromotorNocta[]){localStorage.setItem(KEY,JSON.stringify(eventos));window.dispatchEvent(new Event(EVENT))}
function suscribir(listener:()=>void){window.addEventListener(EVENT,listener);window.addEventListener("storage",listener);return()=>{window.removeEventListener(EVENT,listener);window.removeEventListener("storage",listener)}}
export function useEventosPromotor(){const raw=useSyncExternalStore(suscribir,snapshot,()=>"[]");const [autorizados,setAutorizados]=useState(false);useEffect(()=>{void fetch("/api/promoter-events",{cache:"no-store"}).then(async r=>{if(r.status===401){guardar([]);return;}if(!r.ok)return;const d=await r.json() as {events?:Array<Record<string,unknown>>};const eventos:EventoPromotorNocta[]=(d.events??[]).map(f=>{const det=(f.details??{}) as Record<string,unknown>;const colaboraciones=(f.event_venue_collaborations??[]) as Array<{venues?:{name?:string;city?:string}}>;const tickets=(f.ticket_types??[]) as Array<Record<string,unknown>>;return{id:String(f.external_key),nombre:String(f.name),resumen:String(det.summary??""),descripcion:String(det.description??""),lugarNombre:String(colaboraciones[0]?.venues?.name??det.venue_name??"Por confirmar"),ciudad:String(colaboraciones[0]?.venues?.city??det.city??""),zona:String(det.zone??""),fechaISO:String(f.starts_at),horaFin:f.ends_at?new Date(String(f.ends_at)).toLocaleTimeString("es-CO",{hour:"2-digit",minute:"2-digit",hour12:false}):"",generos:Array.isArray(det.genres)?det.genres.map(String):[],edadMinima:Number(det.min_age??18),dressCode:String(det.dress_code??""),color:String(det.color??"#b644ff"),promotor:String(det.promoter_name??""),estado:({draft:"borrador",pending_venue:"borrador",published:"publicado",closed:"cerrado",cancelled:"cerrado"}[String(f.status)]??"borrador") as EventoPromotorNocta["estado"],tiposEntrada:tickets.map(t=>({id:String(t.id),nombre:String(t.name),precio:Number(t.price_cop),descripcion:String(t.description??""),cupo:Number(t.capacity)})),reservasActivas:Boolean(det.reservations_enabled),listasActivas:Boolean(det.lists_enabled),capacidad:Number(f.capacity),creadoEn:new Date(String(f.created_at)).getTime()};});guardar(eventos);}).catch(()=>undefined).finally(()=>setAutorizados(true));},[]);const eventos=useMemo(()=>parsear(raw),[raw]);return autorizados?eventos:[]}
export function eventoPromotorPorId(id:string){return parsear(snapshot()).find(e=>e.id===id)}
export function crearEventoPromotor(datos:Omit<EventoPromotorNocta,"id"|"estado"|"creadoEn">,idRemoto?:string){if(!datos.nombre.trim()||!datos.lugarNombre.trim()||!datos.promotor.trim()||!datos.tiposEntrada.length)return null;const evento:EventoPromotorNocta={...datos,id:idRemoto??`plan-${Date.now()}`,estado:"borrador",creadoEn:Date.now()};guardar([...parsear(snapshot()),evento]);return evento}
export function actualizarEventoPromotor(id:string,mutar:(evento:EventoPromotorNocta)=>void){const eventos=parsear(snapshot());const evento=eventos.find(e=>e.id===id);if(!evento)return false;mutar(evento);guardar(eventos);void fetch("/api/promoter-events",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({externalKey:id,status:evento.estado==="publicado"?"published":"closed"})}).catch(()=>undefined);return true}
