"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";
import {CollaborationCenter} from "@/components/collaboration-center";
type EventItem={id:string;external_key:string;name:string;status:string;ticket_types?:Array<{id:string;name:string;price_cop:number;capacity:number;tickets?:Array<{id:string;status:string;amount_cop:number}>}>;event_venue_collaborations?:Array<{status:string;venues?:{name:string}}> ;event_sponsors?:Array<{id:string;name:string;contribution_value_cop:number;status:string}>;event_complimentary_allocations?:Array<{id:string;recipient_name:string;quantity:number;status:string}>;promoter_settlements?:Array<{net_cop:number;status:string}>};
type Data={profile?:{public_name:string;bio:string;contact_email?:string;contact_phone?:string};events:EventItem[];team:Array<{id:string;user_id:string;status:string;profiles?:{full_name:string};organization_roles?:Array<{context_role:string;role:string}>}>;analytics:{events:number;published:number;tickets:number;checkedIn:number;grossCop:number;audience:number;impressions:number;views:number;clicks:number;reservations:number}};
const TITLES:Record<string,[string,string]>={tickets:["Tickets","Inventario, ventas y cortesías por evento."],audiencia:["Audiencia","Asistentes únicos, recurrencia y check-in."],alianzas:["Alianzas","Propuestas a establecimientos y patrocinadores."],liquidaciones:["Liquidaciones","Ingresos, cargos, deducciones y pagos."],analitica:["Analítica","Rendimiento comercial y operativo."],equipo:["Equipo","Miembros y permisos de la organización promotora."],configuracion:["Configuración","Perfil público y datos de contacto."]};
export default function PromoterSection(){const {section}=useParams<{section:string}>();const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");const [saving,setSaving]=useState(false);const title=TITLES[section]??["Promotor","Módulo no encontrado."];
async function load(){const r=await fetch("/api/promoter",{cache:"no-store"});const d=await r.json();if(!r.ok){setError(d.error);return}setError("");setData(d)}useEffect(()=>{void fetch("/api/promoter",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>setError(e.message))},[]);
async function create(e:FormEvent<HTMLFormElement>,action:"sponsor"|"courtesy"){e.preventDefault();setSaving(true);const form=e.currentTarget;const raw=Object.fromEntries(new FormData(form));const body={...raw,action,quantity:Number(raw.quantity??0),contributionValueCop:Number(raw.contributionValueCop??0)};const r=await fetch("/api/promoter",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setSaving(false);if(!r.ok)return setError(d.error);form.reset();await load()}
async function profile(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const r=await fetch("/api/promoter",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const d=await r.json();setSaving(false);if(!r.ok)return setError(d.error);await load()}
const tickets=useMemo(()=>data?.events.flatMap(e=>e.ticket_types?.flatMap(t=>t.tickets??[])??[])??[],[data]);
return <main className="flex-1 px-5 py-8 max-w-6xl mx-auto w-full space-y-6"><header><p className="text-xs uppercase tracking-[.2em] text-neon2">Promotor</p><h1 className="text-3xl font-bold mt-1">{title[0]}</h1><p className="text-muted">{title[1]}</p></header>{error&&<p className="card border-danger/40 p-4 text-danger">{error}</p>}
{section==="tickets"&&<><Stats values={[["Emitidas",tickets.length],["Usadas",tickets.filter(t=>t.status==="used").length],["Ingresos",`$${(data?.analytics.grossCop??0).toLocaleString("es-CO")}`]]}/><EventCards events={data?.events??[]}/><ActionForm events={data?.events??[]} kind="courtesy" submit={e=>create(e,"courtesy")} saving={saving}/></>}
{section==="audiencia"&&<><Stats values={[["Alcance único",data?.analytics.audience??0],["Impresiones",data?.analytics.impressions??0],["Vistas",data?.analytics.views??0],["Clics",data?.analytics.clicks??0],["Check-ins",data?.analytics.checkedIn??0],["Conversión",data?.analytics.views?`${Math.round((data.analytics.checkedIn/data.analytics.views)*100)}%`:"0%"]]}/><Empty text="La audiencia se consolida automáticamente desde impresiones, vistas, compras, reservas y check-ins."/></>}
{section==="alianzas"&&<><CollaborationCenter/><div className="grid md:grid-cols-2 gap-4">{data?.events.map(e=><article key={e.id} className="card p-5"><b>{e.name}</b><p className="text-sm text-muted mt-2">Establecimiento: {e.event_venue_collaborations?.[0]?.venues?.name??"Sin propuesta"} · {e.event_venue_collaborations?.[0]?.status??"pendiente"}</p>{e.event_sponsors?.map(s=><p key={s.id} className="text-sm mt-2">{s.name} · {s.status} · ${s.contribution_value_cop.toLocaleString("es-CO")}</p>)}</article>)}</div><ActionForm events={data?.events??[]} kind="sponsor" submit={e=>create(e,"sponsor")} saving={saving}/></>}
{section==="liquidaciones"&&<div className="space-y-3">{data?.events.map(e=>{const s=e.promoter_settlements?.[0];return <article key={e.id} className="card p-5 flex justify-between"><span><b>{e.name}</b><p className="text-sm text-muted">{s?.status??"Pendiente de cierre"}</p></span><b>${Number(s?.net_cop??0).toLocaleString("es-CO")}</b></article>})}</div>}
{section==="analitica"&&<Stats values={[["Impresiones",data?.analytics.impressions??0],["Vistas",data?.analytics.views??0],["Entradas",data?.analytics.tickets??0],["Reservas",data?.analytics.reservations??0],["Check-ins",data?.analytics.checkedIn??0],["Revenue confirmado",`$${(data?.analytics.grossCop??0).toLocaleString("es-CO")}`]]}/>}
{section==="equipo"&&<div className="space-y-3">{data?.team.map(m=><article key={m.id} className="card p-4 flex justify-between"><span><b>{m.profiles?.full_name||m.user_id}</b><p className="text-xs text-muted">{m.organization_roles?.filter(r=>r.context_role==="promoter").map(r=>r.role).join(", ")||"Sin permiso promotor"}</p></span><span className="text-sm text-neon3">{m.status}</span></article>)}</div>}
{section==="configuracion"&&<form onSubmit={profile} className="card p-5 max-w-xl space-y-4"><label className="block text-sm">Nombre público<input name="publicName" required defaultValue={data?.profile?.public_name} className="entrada"/></label><label className="block text-sm">Biografía<textarea name="bio" defaultValue={data?.profile?.bio} className="entrada min-h-24"/></label><label className="block text-sm">Correo<input name="contactEmail" type="email" defaultValue={data?.profile?.contact_email} className="entrada"/></label><label className="block text-sm">Teléfono<input name="contactPhone" defaultValue={data?.profile?.contact_phone} className="entrada"/></label><button disabled={saving} className="btn-neon rounded-xl px-5 py-3">Guardar perfil</button></form>}</main>}
function Stats({values}:{values:Array<[string,string|number]>}){return <section className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">{values.map(([t,v])=><div key={t} className="card p-4"><p className="text-xs text-muted">{t}</p><p className="text-xl font-bold mt-1">{v}</p></div>)}</section>}
function Empty({text}:{text:string}){return <div className="card p-6 text-muted">{text}</div>}
function EventCards({events}:{events:EventItem[]}){return <div className="grid md:grid-cols-2 gap-4">{events.map(e=><article key={e.id} className="card p-5"><div className="flex justify-between"><b>{e.name}</b><Link href={`/promotor/planes/${e.external_key}`} className="text-neon2">Gestionar →</Link></div>{e.ticket_types?.map(t=><p key={t.id} className="text-sm text-muted mt-3">{t.name}: {t.tickets?.length??0}/{t.capacity} · ${t.price_cop.toLocaleString("es-CO")}</p>)}</article>)}</div>}
function ActionForm({events,kind,submit,saving}:{events:EventItem[];kind:"sponsor"|"courtesy";submit:(e:FormEvent<HTMLFormElement>)=>void;saving:boolean}){return <form onSubmit={submit} className="card p-5 grid md:grid-cols-2 gap-3"><h2 className="font-bold md:col-span-2">{kind==="sponsor"?"Agregar patrocinador":"Reservar cortesía"}</h2><select name="eventId" required className="entrada"><option value="">Evento</option>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><input name="name" required placeholder={kind==="sponsor"?"Marca o aliado":"Persona o aliado"} className="entrada"/>{kind==="sponsor"?<><select name="contributionType" className="entrada"><option value="cash">Dinero</option><option value="product">Producto</option><option value="media">Medios</option><option value="other">Otro</option></select><input name="contributionValueCop" type="number" min="0" placeholder="Valor COP" className="entrada"/></>:<><input name="email" type="email" placeholder="Correo" className="entrada"/><input name="quantity" type="number" min="1" max="20" defaultValue="1" className="entrada"/></>}<button disabled={saving} className="btn-neon rounded-xl p-3 md:col-span-2">Guardar</button></form>}
