"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { eventoPorId, formatearFecha, lugarPorId } from "@/lib/discovery";
import { actualizarEstadoReserva, useReservas } from "@/lib/reservations";

export default function DetalleReserva(){const {id}=useParams<{id:string}>();const r=useReservas().find(x=>x.id===id);if(!r)return <main className="p-8 text-muted">Reserva no encontrada.</main>;const e=eventoPorId(r.eventoId);const l=e?lugarPorId(e.lugarId):undefined;return <main className="flex-1 px-5 py-8 max-w-md mx-auto w-full space-y-6"><Link href="/mis-reservas" className="text-sm text-muted">← Mis reservas</Link><section className="card p-6 text-center space-y-5"><div className="text-5xl">{r.estado==="confirmada"?"✓":"◷"}</div><div><p className="text-neon3 text-sm">{l?.nombre}</p><h1 className="text-3xl font-bold">{e?.nombre}</h1>{e&&<p className="text-sm text-muted capitalize mt-2">{formatearFecha(e.fechaISO,true)}</p>}</div><div className="rounded-xl bg-surface2 p-4"><p className="text-xs text-muted">Código de reserva</p><p className="font-mono text-xl font-bold mt-1">{r.codigo}</p></div><div className="grid grid-cols-2 gap-3 text-left"><Dato t="Espacio" v={r.tipoNombre}/><Dato t="Personas" v={String(r.personas)}/><Dato t="Consumo mínimo" v={`$${r.consumoMinimo.toLocaleString("es-CO")}`}/><Dato t="Anticipo" v={`$${r.anticipo.toLocaleString("es-CO")}`}/></div><p className={`rounded-xl p-3 font-bold ${r.estado==="confirmada"?"bg-lime/15 text-lime":r.estado==="pendiente"?"bg-amber/15 text-amber":"bg-muted/15 text-muted"}`}>{r.estado==="pendiente"?"Esperando confirmación del establecimiento":r.estado==="confirmada"?"Reserva confirmada · presenta este código":`Reserva ${r.estado}`}</p></section>{["pendiente","confirmada"].includes(r.estado)&&<button onClick={()=>actualizarEstadoReserva(id,"cancelada")} className="w-full rounded-2xl border border-danger/40 text-danger p-4">Cancelar reserva</button>}<p className="text-xs text-center text-muted">Las solicitudes especiales están sujetas a disponibilidad del establecimiento.</p></main>}
function Dato({t,v}:{t:string;v:string}){return <div><p className="text-xs text-muted">{t}</p><p className="font-semibold mt-1">{v}</p></div>}
