import { NextRequest, NextResponse } from "next/server";
import { crearClienteSupabaseServidor } from "@/lib/supabase/server";

async function contexto(key:string){const supabase=await crearClienteSupabaseServidor();if(!supabase)return {error:NextResponse.json({error:"Supabase no configurado"},{status:503})};const {data:claims}=await supabase.auth.getClaims();if(!claims?.claims?.sub)return {error:NextResponse.json({error:"No autenticado"},{status:401})};const {data:venue}=await supabase.from("venues").select("id,external_key").eq("external_key",key).maybeSingle();if(!venue)return {error:NextResponse.json({error:"Establecimiento no encontrado"},{status:404})};return {supabase,venue,userId:claims.claims.sub};}

export async function GET(_:NextRequest,{params}:{params:Promise<{key:string}>}){const {key}=await params;const ctx=await contexto(key);if(ctx.error)return ctx.error;const {data,error}=await ctx.supabase!.from("venue_runtime_states").select("state,revision,updated_at").eq("venue_id",ctx.venue!.id).maybeSingle();if(error)return NextResponse.json({error:error.message},{status:403});return NextResponse.json({state:data?.state??null,revision:data?.revision??0,updatedAt:data?.updated_at??null});}

export async function PUT(request:NextRequest,{params}:{params:Promise<{key:string}>}){const {key}=await params;const ctx=await contexto(key);if(ctx.error)return ctx.error;const body=await request.json() as {state?:unknown};if(!body.state||typeof body.state!=="object")return NextResponse.json({error:"Estado inválido"},{status:400});const serialized=JSON.stringify(body.state);if(serialized.length>1_500_000)return NextResponse.json({error:"El estado supera el límite permitido"},{status:413});const {data:actual}=await ctx.supabase!.from("venue_runtime_states").select("revision").eq("venue_id",ctx.venue!.id).maybeSingle();const revision=(actual?.revision??0)+1;const {error}=await ctx.supabase!.from("venue_runtime_states").upsert({venue_id:ctx.venue!.id,state:body.state,revision,updated_by:ctx.userId,updated_at:new Date().toISOString()});if(error)return NextResponse.json({error:error.message},{status:403});return NextResponse.json({ok:true,revision});}

