-- Fase 8: operacion nocturna transaccional por subrol.
alter table public.orders add column if not exists assigned_user_id uuid references public.profiles(id) on delete set null;
alter table public.orders add column if not exists delivery_signal jsonb not null default '{}'::jsonb;
alter table public.orders add column if not exists notes text not null default '';
alter table public.orders add column if not exists paid_at timestamptz;
alter table public.orders add column if not exists paid_by uuid references public.profiles(id) on delete set null;
alter table public.orders add column if not exists payment_reference text;

create or replace function public.can_operate_venue(target_venue uuid)
returns boolean language sql stable security definer set search_path='' as $$
 select public.is_platform_owner() or exists(select 1 from public.venue_members vm where vm.venue_id=target_venue and vm.user_id=auth.uid()) or exists(
  select 1 from public.venues v join public.organization_memberships m on m.organization_id=v.organization_id join public.organization_roles r on r.membership_id=m.id
  where v.id=target_venue and m.user_id=auth.uid() and m.status='active' and r.context_role='establishment' and r.role in('owner','admin','establishment_admin','bar','waiter','cashier') and(r.scope_venue_id is null or r.scope_venue_id=target_venue)
 );
$$;
create or replace function public.current_venue_roles(target_venue uuid)returns text[] language sql stable security definer set search_path='' as $$select coalesce(array_agg(distinct role),array[]::text[])from(
 select vm.role::text role from public.venue_members vm where vm.venue_id=target_venue and vm.user_id=auth.uid()
 union all select r.role::text from public.venues v join public.organization_memberships m on m.organization_id=v.organization_id join public.organization_roles r on r.membership_id=m.id where v.id=target_venue and m.user_id=auth.uid() and m.status='active' and r.context_role='establishment' and(r.scope_venue_id is null or r.scope_venue_id=target_venue)
)x;$$;
create or replace function public.create_operational_order(venue_key text,order_key text,service text,zone text,order_items jsonb,subtotal integer,tip integer,total integer,payment_method_value text,payment_status_value text,preorder_at timestamptz,pickup_pin text)returns uuid language plpgsql security definer set search_path='' as $$declare venue uuid;new_id uuid;calculated bigint;begin if auth.uid() is null then raise exception 'AUTH_REQUIRED';end if;select id into venue from public.venues where external_key=venue_key and active;if venue is null then raise exception 'VENUE_NOT_FOUND';end if;if service not in('bar','zone','table')or payment_method_value not in('digital','cash','efectivo','datafono')or payment_status_value not in('paid','pending')or jsonb_typeof(order_items)<>'array'or jsonb_array_length(order_items)=0 then raise exception 'INVALID_ORDER';end if;if preorder_at is not null and preorder_at<now()+interval '30 minutes'then raise exception 'INVALID_PREORDER';end if;select coalesce(sum((x->>'precioUnit')::integer*(x->>'cantidad')::integer),0)into calculated from jsonb_array_elements(order_items)x;if calculated<>subtotal or total<>subtotal+tip or subtotal<0 or tip<0 then raise exception 'INVALID_TOTAL';end if;insert into public.orders(external_key,venue_id,customer_user_id,service_mode,zone_name,items,subtotal_cop,tip_cop,total_cop,payment_method,payment_status,status,preorder_for,pickup_pin_hash)values(order_key,venue,auth.uid(),service,zone,order_items,subtotal,tip,total,payment_method_value,payment_status_value,'new',preorder_at,case when pickup_pin is null then null else encode(digest(pickup_pin,'sha256'),'hex')end)on conflict(external_key)do update set external_key=excluded.external_key returning id into new_id;insert into public.order_status_history(order_id,to_status,actor_id,metadata)select new_id,'new',auth.uid(),jsonb_build_object('source','consumer')where not exists(select 1 from public.order_status_history where order_id=new_id);return new_id;end;$$;
create or replace function public.transition_operational_order(order_key text,next_status text,assignment uuid default null,signal jsonb default null,transition_notes text default '')returns void language plpgsql security definer set search_path='' as $$declare selected public.orders;roles text[];target public.order_status;allowed boolean:=false;begin select * into selected from public.orders where external_key=order_key for update;if not found then raise exception 'ORDER_NOT_FOUND';end if;if not public.can_operate_venue(selected.venue_id)then raise exception 'FORBIDDEN';end if;target:=next_status::public.order_status;roles:=public.current_venue_roles(selected.venue_id);allowed:=public.is_platform_owner()or roles&&array['venue_owner','venue_admin','owner','admin','establishment_admin']or(roles&&array['bartender','bar']and selected.status in('new','preparing','ready')and(target in('preparing','ready')or(selected.service_mode='bar'and target='delivered')))or(roles&&array['waiter']and selected.status in('ready','on_the_way')and target in('on_the_way','delivered','ready'))or(roles&&array['cashier']and target in('delivered','cancelled'));if not allowed then raise exception 'ROLE_CANNOT_TRANSITION';end if;if target='delivered'and selected.payment_status<>'paid'then raise exception 'PAYMENT_REQUIRED';end if;if not((selected.status='new'and target in('preparing','ready','cancelled','expired'))or(selected.status='preparing'and target in('ready','cancelled','expired'))or(selected.status='ready'and target in('on_the_way','delivered','cancelled','expired'))or(selected.status='on_the_way'and target in('ready','delivered','cancelled')))then raise exception 'INVALID_TRANSITION';end if;update public.orders set status=target,assigned_user_id=coalesce(assignment,assigned_user_id),delivery_signal=coalesce(signal,delivery_signal),notes=case when transition_notes<>''then transition_notes else notes end,updated_at=now()where id=selected.id;insert into public.order_status_history(order_id,from_status,to_status,actor_id,metadata)values(selected.id,selected.status,target,auth.uid(),jsonb_build_object('notes',transition_notes));end;$$;
create or replace function public.record_operational_payment(order_key text,method text,reference text default '')returns void language plpgsql security definer set search_path='' as $$declare selected public.orders;roles text[];begin select * into selected from public.orders where external_key=order_key for update;if not found then raise exception 'ORDER_NOT_FOUND';end if;if not public.can_operate_venue(selected.venue_id)then raise exception 'FORBIDDEN';end if;roles:=public.current_venue_roles(selected.venue_id);if not(public.is_platform_owner()or roles&&array['venue_owner','venue_admin','owner','admin','establishment_admin','cashier'])then raise exception 'ROLE_CANNOT_CHARGE';end if;if selected.payment_status='paid'then return;end if;if selected.status in('cancelled','expired')then raise exception 'ORDER_CLOSED';end if;update public.orders set payment_method=method,payment_status='paid',paid_at=now(),paid_by=auth.uid(),payment_reference=nullif(reference,''),updated_at=now()where id=selected.id;insert into public.audit_logs(actor_id,action,entity_type,entity_id,metadata)values(auth.uid(),'order.payment.recorded','order',selected.id,jsonb_build_object('method',method,'amount',selected.total_cop));end;$$;
grant execute on function public.current_venue_roles(uuid),public.create_operational_order(text,text,text,text,jsonb,integer,integer,integer,text,text,timestamptz,text),public.transition_operational_order(text,text,uuid,jsonb,text),public.record_operational_payment(text,text,text)to authenticated;
notify pgrst,'reload schema';
