-- Fase 9: libro economico transversal e idempotente.
create table if not exists public.economic_transactions(
 id uuid primary key default gen_random_uuid(),external_key text not null unique,kind text not null check(kind in('ticket_sale','reservation_deposit','order_payment','point_redemption','promoter_settlement','campaign_spend')),
 status text not null check(status in('pending','reserved','paid','completed','cancelled','refunded','reversed','disputed')),currency text not null default 'COP' check(currency in('COP','PTS')),
 gross_amount bigint not null default 0 check(gross_amount>=0),discount_amount bigint not null default 0 check(discount_amount>=0),fee_amount bigint not null default 0 check(fee_amount>=0),tax_amount bigint not null default 0 check(tax_amount>=0),net_amount bigint not null default 0,
 payer_user_id uuid references public.profiles(id) on delete set null,beneficiary_organization_id uuid references public.organizations(id) on delete set null,venue_id uuid references public.venues(id) on delete set null,event_id uuid references public.events(id) on delete set null,
 source_table text not null,source_id uuid not null,payment_method text,payment_reference text,occurred_at timestamptz not null default now(),settled_at timestamptz,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(source_table,source_id)
);
create index if not exists economic_org_date on public.economic_transactions(beneficiary_organization_id,occurred_at desc);create index if not exists economic_payer_date on public.economic_transactions(payer_user_id,occurred_at desc);create index if not exists economic_event on public.economic_transactions(event_id,kind,status);
create or replace function public.can_view_economic_transaction(target_transaction uuid)returns boolean language sql stable security definer set search_path='' as $$select public.is_platform_owner()or exists(select 1 from public.economic_transactions t where t.id=target_transaction and(t.payer_user_id=auth.uid()or(t.beneficiary_organization_id is not null and exists(select 1 from public.organization_memberships m join public.organization_roles r on r.membership_id=m.id where m.user_id=auth.uid()and m.organization_id=t.beneficiary_organization_id and m.status='active'))));$$;
alter table public.economic_transactions enable row level security;drop policy if exists "economic participants read"on public.economic_transactions;create policy "economic participants read"on public.economic_transactions for select to authenticated using(public.can_view_economic_transaction(id));grant select on public.economic_transactions to authenticated;

create or replace function public.sync_ticket_economic()returns trigger language plpgsql security definer set search_path='' as $$declare org uuid;begin select organization_id into org from public.events where id=new.event_id;insert into public.economic_transactions(external_key,kind,status,currency,gross_amount,net_amount,payer_user_id,beneficiary_organization_id,event_id,source_table,source_id,payment_reference,occurred_at,settled_at,metadata)values('ticket:'||new.id,'ticket_sale',case new.status::text when'paid'then'paid'when'used'then'completed'when'cancelled'then'cancelled'when'refunded'then'refunded'else'pending'end,'COP',new.amount_cop,new.amount_cop,new.holder_user_id,org,new.event_id,'tickets',new.id,new.payment_reference,coalesce(new.purchased_at,new.created_at),case when new.status::text in('paid','used')then coalesce(new.purchased_at,now())else null end,jsonb_build_object('ticket_type_id',new.ticket_type_id))on conflict(source_table,source_id)do update set status=excluded.status,gross_amount=excluded.gross_amount,net_amount=excluded.net_amount,payment_reference=excluded.payment_reference,settled_at=excluded.settled_at,updated_at=now();return new;end;$$;
create or replace function public.sync_order_economic()returns trigger language plpgsql security definer set search_path='' as $$declare org uuid;begin select organization_id into org from public.venues where id=new.venue_id;insert into public.economic_transactions(external_key,kind,status,currency,gross_amount,discount_amount,net_amount,payer_user_id,beneficiary_organization_id,venue_id,source_table,source_id,payment_method,payment_reference,occurred_at,settled_at,metadata)values('order:'||new.id,'order_payment',case when new.status::text='cancelled'then'cancelled'when new.payment_status='paid'and new.status::text='delivered'then'completed'when new.payment_status='paid'then'paid'else'pending'end,'COP',new.total_cop,0,new.total_cop,new.customer_user_id,org,new.venue_id,'orders',new.id,new.payment_method,new.payment_reference,new.created_at,new.paid_at,jsonb_build_object('service_mode',new.service_mode,'tip_cop',new.tip_cop,'status',new.status))on conflict(source_table,source_id)do update set status=excluded.status,gross_amount=excluded.gross_amount,net_amount=excluded.net_amount,payment_method=excluded.payment_method,payment_reference=excluded.payment_reference,settled_at=excluded.settled_at,metadata=excluded.metadata,updated_at=now();return new;end;$$;
create or replace function public.sync_reservation_economic()returns trigger language plpgsql security definer set search_path='' as $$declare org uuid;begin if new.deposit_cop<=0 then return new;end if;select organization_id into org from public.venues where id=new.venue_id;insert into public.economic_transactions(external_key,kind,status,currency,gross_amount,net_amount,payer_user_id,beneficiary_organization_id,venue_id,event_id,source_table,source_id,occurred_at,settled_at,metadata)values('reservation:'||new.id,'reservation_deposit',case new.status::text when'cancelled'then'cancelled'when'completed'then'completed'when'confirmed'then'paid'when'checked_in'then'paid'else'pending'end,'COP',new.deposit_cop,new.deposit_cop,new.customer_user_id,org,new.venue_id,new.event_id,'reservations',new.id,new.created_at,case when new.status::text in('confirmed','checked_in','completed')then new.updated_at else null end,jsonb_build_object('party_size',new.party_size))on conflict(source_table,source_id)do update set status=excluded.status,gross_amount=excluded.gross_amount,net_amount=excluded.net_amount,settled_at=excluded.settled_at,updated_at=now();return new;end;$$;
create or replace function public.sync_redemption_economic()returns trigger language plpgsql security definer set search_path='' as $$declare venue uuid;org uuid;begin select r.venue_id,v.organization_id into venue,org from public.loyalty_rewards r join public.venues v on v.id=r.venue_id where r.id=new.reward_id;insert into public.economic_transactions(external_key,kind,status,currency,gross_amount,net_amount,payer_user_id,beneficiary_organization_id,venue_id,source_table,source_id,occurred_at,settled_at,metadata)values('redemption:'||new.id,'point_redemption',case new.status when'requested'then'reserved'when'delivered'then'completed'when'cancelled'then'reversed'when'rejected'then'cancelled'else'reserved'end,'PTS',new.points,new.points,new.user_id,org,venue,'loyalty_redemptions',new.id,new.created_at,new.redeemed_at,jsonb_build_object('reward_id',new.reward_id))on conflict(source_table,source_id)do update set status=excluded.status,settled_at=excluded.settled_at,updated_at=now();return new;end;$$;
create or replace function public.sync_settlement_economic()returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.economic_transactions(external_key,kind,status,currency,gross_amount,fee_amount,net_amount,beneficiary_organization_id,event_id,source_table,source_id,payment_reference,occurred_at,settled_at,metadata)values('settlement:'||new.id,'promoter_settlement',case new.status when'paid'then'completed'when'disputed'then'disputed'when'approved'then'paid'else'pending'end,'COP',new.gross_cop,new.fees_cop+new.deductions_cop,new.net_cop,new.organization_id,new.event_id,'promoter_settlements',new.id,new.reference,new.created_at,new.paid_at,jsonb_build_object('fees_cop',new.fees_cop,'deductions_cop',new.deductions_cop))on conflict(source_table,source_id)do update set status=excluded.status,gross_amount=excluded.gross_amount,fee_amount=excluded.fee_amount,net_amount=excluded.net_amount,payment_reference=excluded.payment_reference,settled_at=excluded.settled_at,updated_at=now();return new;end;$$;
create or replace function public.sync_activation_economic()returns trigger language plpgsql security definer set search_path='' as $$declare org uuid;begin select organization_id into org from public.brand_campaigns where id=new.campaign_id;insert into public.economic_transactions(external_key,kind,status,currency,gross_amount,net_amount,beneficiary_organization_id,venue_id,event_id,source_table,source_id,occurred_at,settled_at,metadata)values('activation:'||new.id,'campaign_spend',case new.status when'completed'then'completed'when'cancelled'then'cancelled'when'rejected'then'cancelled'else'pending'end,'COP',new.actual_spend_cop,new.actual_spend_cop,org,new.venue_id,new.event_id,'brand_activations',new.id,new.created_at,case when new.status='completed'then new.updated_at else null end,jsonb_build_object('campaign_id',new.campaign_id,'revenue_cop',new.revenue_cop,'units_sold',new.units_sold,'redemptions',new.redemptions))on conflict(source_table,source_id)do update set status=excluded.status,gross_amount=excluded.gross_amount,net_amount=excluded.net_amount,settled_at=excluded.settled_at,metadata=excluded.metadata,updated_at=now();return new;end;$$;

drop trigger if exists economic_ticket_sync on public.tickets;create trigger economic_ticket_sync after insert or update on public.tickets for each row execute function public.sync_ticket_economic();drop trigger if exists economic_order_sync on public.orders;create trigger economic_order_sync after insert or update on public.orders for each row execute function public.sync_order_economic();drop trigger if exists economic_reservation_sync on public.reservations;create trigger economic_reservation_sync after insert or update on public.reservations for each row execute function public.sync_reservation_economic();drop trigger if exists economic_redemption_sync on public.loyalty_redemptions;create trigger economic_redemption_sync after insert or update on public.loyalty_redemptions for each row execute function public.sync_redemption_economic();drop trigger if exists economic_settlement_sync on public.promoter_settlements;create trigger economic_settlement_sync after insert or update on public.promoter_settlements for each row execute function public.sync_settlement_economic();drop trigger if exists economic_activation_sync on public.brand_activations;create trigger economic_activation_sync after insert or update on public.brand_activations for each row execute function public.sync_activation_economic();
-- Backfill set-based invocations are generated by harmless self-updates, activating the idempotent triggers.
update public.tickets set amount_cop=amount_cop;update public.orders set total_cop=total_cop;update public.reservations set deposit_cop=deposit_cop where deposit_cop>0;update public.loyalty_redemptions set points=points;update public.promoter_settlements set gross_cop=gross_cop;update public.brand_activations set actual_spend_cop=actual_spend_cop;
notify pgrst,'reload schema';
