-- Fase 7: colaboracion transversal sin duplicar eventos, campanas u organizaciones.
create table if not exists public.organization_collaborations(
 id uuid primary key default gen_random_uuid(),source_organization_id uuid not null references public.organizations(id) on delete cascade,target_organization_id uuid not null references public.organizations(id) on delete cascade,
 collaboration_type text not null check(collaboration_type in('event_venue','event_sponsor','campaign_venue','campaign_event','commercial_alliance')),
 event_id uuid references public.events(id) on delete cascade,campaign_id uuid references public.brand_campaigns(id) on delete cascade,
 status text not null default 'proposed' check(status in('proposed','countered','accepted','rejected','cancelled','completed')),
 title text not null,terms jsonb not null default '{}'::jsonb,message text not null default '',last_actor_organization_id uuid not null references public.organizations(id),created_by uuid not null references public.profiles(id),
 expires_at timestamptz,accepted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(source_organization_id<>target_organization_id),check(event_id is not null or campaign_id is not null or collaboration_type='commercial_alliance')
);
create table if not exists public.collaboration_history(
 id bigint generated always as identity primary key,collaboration_id uuid not null references public.organization_collaborations(id) on delete cascade,actor_user_id uuid not null references public.profiles(id),actor_organization_id uuid not null references public.organizations(id),action text not null,previous_status text,new_status text not null,terms jsonb not null default '{}'::jsonb,message text not null default '',created_at timestamptz not null default now()
);
create index if not exists collaborations_source on public.organization_collaborations(source_organization_id,status);create index if not exists collaborations_target on public.organization_collaborations(target_organization_id,status);
create or replace function public.collaboration_directory()returns table(id uuid,name text,business_type text,contexts text[])language sql stable security definer set search_path='' as $$select o.id,o.name,o.business_type::text,array_agg(c.role::text order by c.role::text) from public.organizations o join public.organization_contexts c on c.organization_id=o.id and c.active where exists(select 1 from public.user_active_contexts ac where ac.user_id=auth.uid() and ac.organization_id is not null and ac.organization_id<>o.id) group by o.id,o.name,o.business_type order by o.name;$$;
create or replace function public.can_participate_in_collaboration(target_collaboration uuid)returns boolean language sql stable security definer set search_path='' as $$select public.is_platform_owner() or exists(select 1 from public.organization_collaborations c join public.organization_memberships m on m.organization_id in(c.source_organization_id,c.target_organization_id) join public.organization_roles r on r.membership_id=m.id where c.id=target_collaboration and m.user_id=auth.uid() and m.status='active' and r.role in('owner','admin','establishment_admin'));$$;
create or replace function public.create_organization_collaboration(target_organization uuid,collaboration_kind text,collaboration_title text,collaboration_message text,linked_event uuid,linked_campaign uuid,collaboration_terms jsonb,collaboration_expires_at timestamptz default null)returns uuid language plpgsql security definer set search_path='' as $$declare source_org uuid;new_id uuid;begin select organization_id into source_org from public.user_active_contexts where user_id=auth.uid();if source_org is null or source_org=target_organization or not exists(select 1 from public.organizations where id=target_organization)then raise exception 'INVALID_ORGANIZATIONS';end if;if not(public.can_manage_organization(source_org) or public.can_manage_promoter_organization(source_org) or public.can_manage_brand_organization(source_org))then raise exception 'FORBIDDEN';end if;if collaboration_kind not in('event_venue','event_sponsor','campaign_venue','campaign_event','commercial_alliance')then raise exception 'INVALID_TYPE';end if;if nullif(btrim(collaboration_title),'')is null or(linked_event is null and linked_campaign is null and collaboration_kind<>'commercial_alliance')then raise exception 'INCOMPLETE_COLLABORATION';end if;if linked_event is not null and not exists(select 1 from public.events where id=linked_event and organization_id in(source_org,target_organization))then raise exception 'EVENT_OUTSIDE_PARTIES';end if;if linked_campaign is not null and not exists(select 1 from public.brand_campaigns where id=linked_campaign and organization_id in(source_org,target_organization))then raise exception 'CAMPAIGN_OUTSIDE_PARTIES';end if;if collaboration_expires_at is not null and collaboration_expires_at<=now()then raise exception 'INVALID_EXPIRY';end if;insert into public.organization_collaborations(source_organization_id,target_organization_id,collaboration_type,event_id,campaign_id,title,message,terms,last_actor_organization_id,created_by,expires_at)values(source_org,target_organization,collaboration_kind,linked_event,linked_campaign,btrim(collaboration_title),coalesce(collaboration_message,''),coalesce(collaboration_terms,'{}'),source_org,auth.uid(),collaboration_expires_at)returning id into new_id;insert into public.collaboration_history(collaboration_id,actor_user_id,actor_organization_id,action,new_status,terms,message)values(new_id,auth.uid(),source_org,'proposed','proposed',coalesce(collaboration_terms,'{}'),coalesce(collaboration_message,''));insert into public.audit_logs(actor_id,action,entity_type,entity_id,metadata)values(auth.uid(),'collaboration.proposed','organization_collaboration',new_id,jsonb_build_object('source',source_org,'target',target_organization));return new_id;end;$$;
create or replace function public.respond_to_collaboration(target_collaboration uuid,new_decision text,new_terms jsonb default null,response_message text default '')returns void language plpgsql security definer set search_path='' as $$declare c public.organization_collaborations;actor_org uuid;next_status text;begin select * into c from public.organization_collaborations where id=target_collaboration for update;if not found then raise exception 'COLLABORATION_NOT_FOUND';end if;select ac.organization_id into actor_org from public.user_active_contexts ac where ac.user_id=auth.uid();if actor_org is null or actor_org not in(c.source_organization_id,c.target_organization_id) or not public.can_participate_in_collaboration(c.id) then raise exception 'FORBIDDEN';end if;if c.status not in('proposed','countered') then raise exception 'COLLABORATION_CLOSED';end if;if new_decision not in('countered','accepted','rejected','cancelled') then raise exception 'INVALID_DECISION';end if;if new_decision='cancelled' and actor_org<>c.source_organization_id then raise exception 'ONLY_SOURCE_CAN_CANCEL';end if;if new_decision in('accepted','rejected') and actor_org=c.last_actor_organization_id then raise exception 'OTHER_PARTY_MUST_DECIDE';end if;next_status:=new_decision;insert into public.collaboration_history(collaboration_id,actor_user_id,actor_organization_id,action,previous_status,new_status,terms,message)values(c.id,auth.uid(),actor_org,new_decision,c.status,next_status,coalesce(new_terms,c.terms),coalesce(response_message,''));update public.organization_collaborations set status=next_status,terms=coalesce(new_terms,terms),message=coalesce(response_message,''),last_actor_organization_id=actor_org,accepted_at=case when next_status='accepted' then now() else null end,updated_at=now() where id=c.id;insert into public.audit_logs(actor_id,action,entity_type,entity_id,metadata)values(auth.uid(),'collaboration.'||next_status,'organization_collaboration',c.id,jsonb_build_object('actor_organization_id',actor_org));end;$$;
alter table public.organization_collaborations enable row level security;alter table public.collaboration_history enable row level security;
drop policy if exists "collaboration participants read" on public.organization_collaborations;create policy "collaboration participants read" on public.organization_collaborations for select to authenticated using(public.can_participate_in_collaboration(id));
drop policy if exists "collaboration source create" on public.organization_collaborations;create policy "collaboration source create" on public.organization_collaborations for insert to authenticated with check(public.can_manage_organization(source_organization_id) or public.can_manage_promoter_organization(source_organization_id) or public.can_manage_brand_organization(source_organization_id));
drop policy if exists "collaboration history read" on public.collaboration_history;create policy "collaboration history read" on public.collaboration_history for select to authenticated using(public.can_participate_in_collaboration(collaboration_id));
grant select,insert on public.organization_collaborations to authenticated;grant select on public.collaboration_history to authenticated;grant execute on function public.collaboration_directory(),public.can_participate_in_collaboration(uuid),public.create_organization_collaboration(uuid,text,text,text,uuid,uuid,jsonb,timestamptz),public.respond_to_collaboration(uuid,text,jsonb,text) to authenticated;
notify pgrst,'reload schema';
