"use client";

import {useCallback,useEffect,useState} from "react";

type Reporte={checked_at:string;tables_without_rls:string[];orphan_events:number;orphan_conecta:number;oversold_ticket_types:number;invalid_reservations:number;platform_owners:number;audit_entries:number};

export default function Integridad(){
  const[reporte,setReporte]=useState<Reporte|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);
  const cargar=useCallback(async()=>{setLoading(true);setError("");const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),15000);try{const r=await fetch("/api/admin/integrity",{cache:"no-store",signal:controller.signal});const contentType=r.headers.get("content-type")??"";const d=contentType.includes("application/json")?await r.json():{};if(!r.ok)throw new Error(d.error??`No fue posible ejecutar la auditoría (${r.status})`);setReporte(d.report)}catch(reason){setError(reason instanceof DOMException&&reason.name==="AbortError"?"La auditoría tardó demasiado. Inténtalo nuevamente.":reason instanceof Error?reason.message:"No fue posible ejecutar la auditoría")}finally{window.clearTimeout(timeout);setLoading(false)}},[]);
  useEffect(()=>{void Promise.resolve().then(cargar)},[cargar]);
  const checks=reporte?[{n:"Tablas sin RLS",v:reporte.tables_without_rls.length},{n:"Eventos huérfanos",v:reporte.orphan_events},{n:"Conecta huérfanos",v:reporte.orphan_conecta},{n:"Localidades sobrevendidas",v:reporte.oversold_ticket_types},{n:"Reservas inválidas",v:reporte.invalid_reservations}]:[];
  return <main className="flex-1 px-5 py-8 max-w-4xl mx-auto w-full space-y-6"><header><p className="text-xs uppercase text-neon2">Auditoría automática</p><h1 className="text-3xl font-bold">Integridad de NOCTA</h1><p className="text-sm text-muted mt-1">Controles de consistencia y seguridad de la plataforma.</p></header>{error&&<section className="card border-danger/40 p-4"><p role="alert" className="text-danger">{error}</p><button type="button" onClick={()=>void cargar()} className="btn-neon rounded-xl px-4 py-2 mt-4">Reintentar</button></section>}{loading&&!reporte&&<p className="text-muted" role="status">Ejecutando controles…</p>}{reporte&&<><div className="flex justify-end"><button type="button" disabled={loading} onClick={()=>void cargar()} className="rounded-xl border border-line px-4 py-2 disabled:opacity-50">{loading?"Actualizando…":"Actualizar"}</button></div><section className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{checks.map(c=><div key={c.n} className={`card p-4 ${c.v?"border-danger/50":"border-lime/40"}`}><p className="text-xs text-muted">{c.n}</p><p className="text-2xl font-bold mt-1">{c.v}</p><p className={`text-xs ${c.v?"text-danger":"text-lime"}`}>{c.v?"Requiere revisión":"Correcto"}</p></div>)}</section><section className="card p-5 text-sm"><p>Propietarios de plataforma: <b>{reporte.platform_owners}</b></p><p>Registros de auditoría: <b>{reporte.audit_entries}</b></p><p className="text-xs text-muted mt-3">Última revisión: {new Date(reporte.checked_at).toLocaleString("es-CO")}</p></section></>}
  </main>;
}
